/**
 * Invoicex
 * Copyright (c) 2005,2006,2007 Marco Ceccarelli, Tnx snc
 *
 * Questo software è soggetto, e deve essere distribuito con la licenza  
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 * 
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */



/*

 * JInternalFrameStampaMovimenti.java

 *

 * Created on 22 gennaio 2003, 23.33

 */



package gestioneFatture.magazzino;

import it.tnx.Db;
import java.util.*;

import java.text.*;

import javax.swing.*;

import javax.swing.text.*;

import java.sql.*;

import java.io.*;



import gestioneFatture.*;

import gestioneFatture.magazzino.print.*;

/**

 *

 * @author  marco

 */

public class JInternalFrameStampaMovimenti extends javax.swing.JInternalFrame {

  MaskFormatter formatter = null;

  

  /** Creates new form JInternalFrameStampaMovimenti */

  public JInternalFrameStampaMovimenti() {

    try {

      formatter = new MaskFormatter("##/##/##");

      formatter.setPlaceholderCharacter('_');

    } catch (Exception err) {

      err.printStackTrace();

    }

    

    initComponents();

    

    //carico combo

    this.comCausale.dbClearList();

    this.comCausale.dbAddElement("<tutte le causali>", "T");

    this.comCausale.dbOpenList(Db.getConn(), "select descrizione, codice from tipi_causali_magazzino");

    

    //impost data iniziale a inizio anno

    this.forDaData.setText("01/01/" + it.tnx.Util.getYearString());

  }

  

  private String getDateToMysql(String value) {

    String ret = "";

    

    DateFormat myFormat = new SimpleDateFormat("dd/MM/yy");

    DateFormat myFormatSql = new SimpleDateFormat("yyyy-MM-dd");

    myFormat.setLenient(false);

    try {

      java.util.Date myDate = myFormat.parse(value);

      ret = myFormatSql.format(myDate);

      return ret;

    } catch (Exception err) {      

      return "";

    }

  }

  

  /** This method is called from within the constructor to

   * initialize the form.

   * WARNING: Do NOT modify this code. The content of this method is

   * always regenerated by the Form Editor.

   */

  private void initComponents() {//GEN-BEGIN:initComponents

    jPanel1 = new javax.swing.JPanel();

    forDaData = new javax.swing.JFormattedTextField();

    forAData = new javax.swing.JFormattedTextField();

    jLabel1 = new javax.swing.JLabel();

    jLabel2 = new javax.swing.JLabel();

    comCausale = new tnxbeans.tnxComboField();

    jLabel3 = new javax.swing.JLabel();

    cheGiacenze = new javax.swing.JCheckBox();

    jPanel2 = new javax.swing.JPanel();

    jPanel3 = new javax.swing.JPanel();

    butStampa1 = new javax.swing.JButton();

    butStampa = new javax.swing.JButton();

    butStampa2 = new javax.swing.JButton();



    setClosable(true);

    setTitle("Stampa movimenti di magazzino");

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());



    jPanel1.add(forDaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 90, -1));



    jPanel1.add(forAData, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 95, -1));



    jLabel1.setText("da data");

    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));



    jLabel2.setText("a data");

    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 20));



    comCausale.setDbNomeCampo("causale");

    comCausale.setDbRiempire(false);

    comCausale.setDbSalvare(false);

    comCausale.setDbTrovaMentreScrive(true);

    jPanel1.add(comCausale, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 60, 160, 20));



    jLabel3.setText("causale");

    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 60, 60, 20));



    cheGiacenze.setText("Giacenza");

    cheGiacenze.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

    cheGiacenze.addActionListener(new java.awt.event.ActionListener() {

      public void actionPerformed(java.awt.event.ActionEvent evt) {

        cheGiacenzeActionPerformed(evt);

      }

    });



    jPanel1.add(cheGiacenze, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));



    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);



    getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);



    butStampa1.setText("Annulla");

    butStampa1.addActionListener(new java.awt.event.ActionListener() {

      public void actionPerformed(java.awt.event.ActionEvent evt) {

        butStampa1ActionPerformed(evt);

      }

    });



    jPanel3.add(butStampa1);



    butStampa.setText("Stampa");

    butStampa.addActionListener(new java.awt.event.ActionListener() {

      public void actionPerformed(java.awt.event.ActionEvent evt) {

        butStampaActionPerformed(evt);

      }

    });



    jPanel3.add(butStampa);



    butStampa2.setText("Stampa e prepara Email");

    butStampa2.addActionListener(new java.awt.event.ActionListener() {

      public void actionPerformed(java.awt.event.ActionEvent evt) {

        butStampa2ActionPerformed(evt);

      }

    });



    jPanel3.add(butStampa2);



    getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);



    pack();

  }//GEN-END:initComponents



  private void butStampa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStampa2ActionPerformed

      butStampaActionPerformed(null);

    

      //copio il file della fattura per mandarlo via mail

      //prima pero' elimino altri files

      File d = new File(main.wd + "tempEmail");

      Util.deleteFilesFromDir(d);

      File fs = null;

      File fd = null;

      if (this.cheGiacenze.isSelected() == true) {

        fs = new File(main.wd + "tempStampaGiacenzeMagazzino.pdf");

        fd = new File(main.wd + "tempEmail/stampa_giacenze.pdf");

      } else {

        fs = new File(main.wd + "tempStampaMovimentiMagazzino.pdf");

        fd = new File(main.wd + "tempEmail/stampa_movimenti.pdf");

      }

      try {

        Util.copyFile(fs, fd);      

      } catch (Exception err) {

        err.printStackTrace();

      }

      //lancio la cartella

      try {

        Util.start(Util.getPathFromFullFileName(fd.getCanonicalPath(),"\\"));

      } catch (Exception err) {

        err.printStackTrace();

      }



  }//GEN-LAST:event_butStampa2ActionPerformed



  private void cheGiacenzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheGiacenzeActionPerformed

    if (cheGiacenze.isSelected() == true) {

      this.comCausale.setEnabled(false);

    } else {

      this.comCausale.setEnabled(true);

    }

  }//GEN-LAST:event_cheGiacenzeActionPerformed



  private void butStampa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStampa1ActionPerformed

    this.dispose();

  }//GEN-LAST:event_butStampa1ActionPerformed



  private void butStampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStampaActionPerformed

    // Add your handling code here:

    String sql = "";

    ResultSet resu;

    

    if (this.cheGiacenze.isSelected() == true) {

      //select per giacenza

      sql += "SELECT  articolo, articoli.descrizione, sum(quantita * segno) FROM movimenti_magazzino left join tipi_causali_magazzino on movimenti_magazzino.causale = tipi_causali_magazzino.codice ";

      sql += " left join articoli on movimenti_magazzino.articolo = articoli.codice";

      sql += " where 1 = 1";    

    } else {

      //select per stampa movimenti semplice

      sql += "select data, causale, tipi_causali_magazzino.descrizione, articolo, articoli.descrizione, quantita";

      sql += " from movimenti_magazzino left join articoli on movimenti_magazzino.articolo = articoli.codice";

      sql += " left join tipi_causali_magazzino on movimenti_magazzino.causale = tipi_causali_magazzino.codice";

      sql += " where 1 = 1";      

    }

    //controllo le date    

    if (this.forDaData.getText().length() > 0) {

      if (this.getDateToMysql(this.forDaData.getText()).length() > 0) {

        sql += " and data >= '" + this.getDateToMysql(this.forDaData.getText()) + "'";

      } else {

        javax.swing.JOptionPane.showMessageDialog(this, "La data di partenza non e' valida");

        return;

      }

    }

    //data di fine

    if (this.forAData.getText().length() > 0) {

      if (this.getDateToMysql(this.forAData.getText()).length() > 0) {

        sql += " and data <= '" + this.getDateToMysql(this.forAData.getText()) + "'";

      } else {

        javax.swing.JOptionPane.showMessageDialog(this, "La data di fine non e' valida");

        return;

      }

    }

    if (this.cheGiacenze.isSelected() == true) {

      //faccio stampa giacenze

      //debug

      sql += " group by articolo order by articolo";

      System.out.println("print_magazzino_giacenze:sql:" + sql);

      resu = Db.openResultSet(sql);

      if (resu != null) {

        String titolo = "Stampa giacenze magazzino - stampata " + it.tnx.Util.getDateTimeStringITALIAN(java.text.DateFormat.FULL, java.text.DateFormat.SHORT);

        titolo += "\ndal: " + this.forDaData.getText() + " al: " + this.forAData.getText();

        PrintGiacenze print = new PrintGiacenze(resu, titolo);

      }        

    } else {

      //faccio stampa a elenco normale

      //controllo causale

      if (this.comCausale.getSelectedIndex() > 0) {

        sql += " and causale = " + this.comCausale.getSelectedKey();

      }



      //debug

      System.out.println("print_magazzino:sql:" + sql);

      resu = Db.openResultSet(sql);

      if (resu != null) {

        PrintMovimenti print = new PrintMovimenti(resu);

      }

    }

  }//GEN-LAST:event_butStampaActionPerformed

  

  

  // Variables declaration - do not modify//GEN-BEGIN:variables

  private javax.swing.JPanel jPanel3;

  private javax.swing.JPanel jPanel2;

  private javax.swing.JPanel jPanel1;

  private javax.swing.JButton butStampa2;

  private javax.swing.JButton butStampa1;

  private javax.swing.JFormattedTextField forDaData;

  private javax.swing.JFormattedTextField forAData;

  private javax.swing.JButton butStampa;

  private tnxbeans.tnxComboField comCausale;

  private javax.swing.JCheckBox cheGiacenze;

  private javax.swing.JLabel jLabel3;

  private javax.swing.JLabel jLabel2;

  private javax.swing.JLabel jLabel1;

  // End of variables declaration//GEN-END:variables

  

}

