/**
 * Invoicex
 * Copyright (c) 2005,2006,2007,2008,2009 Marco Ceccarelli, Tnx snc
 *
 * Questo software è soggetto, e deve essere distribuito con la licenza
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 *
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */
package it.tnx.invoicex.gui;

import gestioneFatture.Db;
import gestioneFatture.main;
import it.tnx.Util;
import it.tnx.commons.CastUtils;
import it.tnx.commons.DbUtils;
import it.tnx.commons.FxUtils;
import it.tnx.commons.SwingUtils;
import it.tnx.invoicex.Attivazione;
import it.tnx.invoicex.data.DatiAzienda;
import java.awt.Color;
import java.io.BufferedInputStream;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author mceccarelli
 */
public class JDialogHelpAss extends javax.swing.JDialog {

    public boolean si = false;
    public boolean tv = true;
    public boolean no = false;

    /** Creates new form JDialogHelpAss */
    public JDialogHelpAss(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        String msg = "";
        String versione = main.fileIni.getValue("cache", "versione", "Base");

        //debug
//        versione = "Base";
//        versione = "Professional";
//        versione = "Enterprise";

        if (versione.equalsIgnoreCase("Base")) {
            msg = "<html><b>L'assistenza</b> è riservata a chi acquista <b>Invoicex Professional, Professional Plus o Enterprise</b><br>Per informazioni clicca sul link sottostante</html>";
            jLabel2.setText(msg);
        } else if (versione.startsWith("Professional")) {
            msg = "<html>Usando questa funzione puoi inviare una mail di richiesta d'assistenza <br>oppure richiedere il collegamento del tuo computer verso un tecnico della TNX.<br>Per avere assistenza telefonica devi acquistare <b>Invoicex Enterprise</b> (vedi il link sotto).";
            jLabel2.setText(msg);
        } else {//enterprise
            msg = "<html>Usando questa funzione puoi inviare una mail di richiesta d'assistenza <br>oppure richiedere il collegamento del tuo computer verso un tecnico della TNX.<br>Prima di procedere contatta la TNX allo 0577 1606038.";
            jLabel2.setText(msg);
            jXHyperlink1.setVisible(false);
        }

        //leggo email mittente da dati anagrafici
        try {
            email.setText(CastUtils.toString(DbUtils.getObject(Db.getConn(), "select email from dati_azienda")));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        vnc = new javax.swing.JRadioButton();
        teamv = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Invoicex");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/22x22/apps/system-users.png"))); // NOI18N
        jLabel1.setText("Assistenza");

        jLabel2.setText("<html> Usando questa funzione puoi inviare una mail di richiesta d'assistenza <br>oppure richiedere il collegamento del tuo computer verso un tecnico della TNX.<br> Prima di procedere contatta la TNX allo 0577 1606038 oppure 0577 980701.<br> Per avere assistenza telefonica devi aver acquistato <b>Invoicex Enterprise</b>.<br> Se non vuoi eseguire il collegamento semplicemente chiudi la finestra.<br>");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/apps/internet-mail.png"))); // NOI18N
        jButton1.setText("Invia messaggio");
        jButton1.addActionListener(formListener);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/apps/system-users.png"))); // NOI18N
        jButton3.setText("Condivisione Desktop");
        jButton3.addActionListener(formListener);

        jButton2.setText("Chiudi");
        jButton2.addActionListener(formListener);

        jXHyperlink1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/apps/internet-web-browser.png"))); // NOI18N
        jXHyperlink1.setText("Sito web www.invoicex.it");
        jXHyperlink1.addActionListener(formListener);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Messaggio");

        buttonGroup1.add(vnc);
        vnc.setText("VNC");

        buttonGroup1.add(teamv);
        teamv.setSelected(true);
        teamv.setText("TeamViewer");

        jLabel4.setText("Email Mittente");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jXHyperlink1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 106, Short.MAX_VALUE)
                        .add(teamv)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(vnc)
                        .add(18, 18, 18)
                        .add(jButton3))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .add(jButton1)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(email, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jXHyperlink1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(email, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton3)
                    .add(vnc)
                    .add(teamv))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == jButton1) {
                JDialogHelpAss.this.jButton1ActionPerformed1(evt);
            }
            else if (evt.getSource() == jButton3) {
                JDialogHelpAss.this.jButton3ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                JDialogHelpAss.this.jButton2ActionPerformed(evt);
            }
            else if (evt.getSource() == jXHyperlink1) {
                JDialogHelpAss.this.jXHyperlink1ActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jXHyperlink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink1ActionPerformed
        try {
            SwingUtils.openUrl(new URL("http://www.invoicex.it/Acquista-Acquista-il-programma/&i=" + main.attivazione.getIdRegistrazione()));
        } catch (Exception ex) {
            SwingUtils.showErrorMessage(this, ex.toString());
        }
    }//GEN-LAST:event_jXHyperlink1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        no = true;
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        si = true;
        if (teamv.isSelected()) {
            tv = true;
        } else {
            tv = false;
        }
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed1

        //controllo email
        String expression = "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Z]{2,4}$";
        CharSequence inputStr = email.getText();
        Pattern pattern = Pattern.compile(expression,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(inputStr);
        if(!matcher.matches()) {
            FxUtils.fadeBackground(email, Color.red);
            SwingUtils.showErrorMessage(this, "Inserire un indirizzo email mittente valido !");
            return;
        }

        String versione = main.fileIni.getValue("cache", "versione", "Base");
        try {
            SwingUtils.mouse_wait(this);

            Attivazione attivazione = new Attivazione();
            DatiAzienda dati = attivazione.getDatiAzienda();
            String surl = "http://www.tnx.it/pagine/invoicex_server/m.php?";
            surl += "&ver=" + URLEncoder.encode(main.version.toString()) + "";
            surl += "&ver2=" + URLEncoder.encode(main.version.toString() + " " + main.build.toString()) + "";
            surl += "&email=" + URLEncoder.encode(email.getText()) + "";
            surl += "&id_registrazione=" + URLEncoder.encode(Util.nz(main.attivazione.getIdRegistrazione())) + "";
            surl += "&ragione_sociale=" + URLEncoder.encode(dati.getRagione_sociale(), "UTF-8") + "";
            surl += "&telefono=" + URLEncoder.encode(dati.getTelefono()) + "";
            surl += "&os=" + URLEncoder.encode(System.getProperty("os.name"));
            surl += "&versione=" + URLEncoder.encode(main.versione);
            surl += "&msg=" + URLEncoder.encode(jTextArea1.getText(), "UTF-8");
            URL url = new URL(surl);
            System.out.println("url:" + url);
            URLConnection conn = url.openConnection();

            int size = conn.getContentLength();

            if (size < 0) {
                size = 1024;
            }

            BufferedInputStream bufin = new BufferedInputStream(conn.getInputStream());
            byte[] bytea = new byte[size];
            int readed = bufin.read(bytea);
            String content = new String(bytea, 0, readed);

            System.out.println("m: response: " + content);
            if (content.equals("OK")) {
                SwingUtils.showInfoMessage(this, "Richiesta inviata, se necessario sarai ricontattato telefonicamente, altrimenti via email");
                no = true;
                dispose();
            } else {
                SwingUtils.showErrorMessage(this, "Errore durante l'invio della richiesta\n" + content);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        SwingUtils.mouse_def(this);
        no = true;
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDialogHelpAss dialog = new JDialogHelpAss(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JTextField email;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextArea jTextArea1;
    public org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    public javax.swing.JRadioButton teamv;
    public javax.swing.JRadioButton vnc;
    // End of variables declaration//GEN-END:variables
}
