/**
 * Invoicex
 * Copyright (c) 2005,2006,2007,2008,2009 Marco Ceccarelli, Tnx snc
 *
 * Questo software è soggetto, e deve essere distribuito con la licenza
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 *
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */


/*
 * JDialogDatiAzienda.java
 *
 * Created on 20 agosto 2007, 15.26
 */

package it.tnx.invoicex.gui;

import it.tnx.Db;
import gestioneFatture.main;
import it.tnx.commons.DbUtils;
import it.tnx.commons.SwingUtils;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.ToolTipManager;

/**
 *
 * @author  mceccarelli
 */
public class JDialogDatiAzienda extends javax.swing.JDialog {
    
    public boolean annullato = false;
    
    /** Creates new form JDialogDatiAzienda */
    public JDialogDatiAzienda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        ToolTipManager ttm = ToolTipManager.sharedInstance();
        ttm.setDismissDelay(15000);
        ttm.setInitialDelay(200);
        
        leggiDatiDaDb();
//        Boolean registraini = main.fileIni.getValueBoolean("varie", "dati_azienda_registra_invoicex", true);
        registra.setSelected(true);
        main.fileIni.setValue("varie", "dati_azienda_registra_invoicex", registra.isSelected());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butConferma = new javax.swing.JButton();
        butAnnulla = new javax.swing.JButton();
        texRagioneSociale = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        texPartitaIva = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        texCodiceFiscale = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        texIndirizzo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        texCap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        texLocalita = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        texProv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        texTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        texFax = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        texEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        texWeb = new javax.swing.JTextField();
        registra = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dati Azienda");

        butConferma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butConferma.setText("Conferma");
        butConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConfermaActionPerformed(evt);
            }
        });

        butAnnulla.setText("Annulla");
        butAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnullaActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Ragione sociale");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Partita Iva");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Codice Fiscale");

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD, jLabel4.getFont().getSize()+2));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/48x48.gif"))); // NOI18N
        jLabel4.setText("Inserisci i dati anagrafici dell'azienda");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Indirizzo");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Cap");

        texCap.setColumns(10);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Localita");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Prov.");

        texProv.setColumns(3);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Telefono");

        texTelefono.setColumns(10);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Fax");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Sito Web");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Email");

        registra.setSelected(true);
        registra.setText("Confermo la registrazione del mio di Invoicex");
        registra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/22x22/apps/help-browser.png"))); // NOI18N
        jLabel13.setToolTipText("<html>\nSe hai la versione Base di Invoicex selezionando questa casella i dati anagrafici di cui sopra<br> verranno inviati a TNX snc per il solo scopo statistico e non verranno ceduti a terzi.<br>\nSe hai Invoicex Professional, Professional Plus o Enterprise verranno anche utilizzati per la verifica della tua licenza\n</html>");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel4)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(registra)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel13)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(butAnnulla)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(butConferma))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, texCodiceFiscale)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, texPartitaIva)
                            .add(texRagioneSociale)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(jLabel11))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(texIndirizzo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .add(texCap, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jLabel7)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(texLocalita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 224, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jLabel8)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(texProv))
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(texWeb)
                                        .add(texTelefono))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel10)
                                        .add(jLabel12))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(texFax)
                                        .add(texEmail)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(texRagioneSociale, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(texPartitaIva, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(texCodiceFiscale, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(texIndirizzo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jLabel6)
                    .add(texProv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(texLocalita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7)
                    .add(texCap, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(texTelefono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10)
                    .add(texFax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(texEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(butConferma)
                            .add(butAnnulla)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11)
                            .add(texWeb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel12))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(registra)
                            .add(jLabel13))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnullaActionPerformed
//        if (texRagioneSociale.getText().length() == 0) {
//            texRagioneSociale.setText("Azienda demo");
//            texPartitaIva.setText("1234567890ABC");
//            texCodiceFiscale.setText("1234567890ABC");
//            scriviDatiSuDb();
//        }
        annullato = true;
        dispose();
    }//GEN-LAST:event_butAnnullaActionPerformed

    private void butConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConfermaActionPerformed
        if (controllaDati()) {
            scriviDatiSuDb();
            gestioneFatture.main.attivazione.setDatiAziendaInseriti(true);
            
            //memorizzo i dati sull'intestazione dei documenti
            if (JOptionPane.showConfirmDialog(this, "Vuoi aggiungere questi dati sulle intestazioni dei documenti in stampa ?\nSe l'intestazione delle stampe era già corretta clicca su No", "Attenzione", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    String sql = "update dati_azienda set ";
                    sql += " intestazione_riga1 = " + Db.pc(texRagioneSociale.getText(), "VARCHAR");
                    sql += " ,intestazione_riga2 = " + Db.pc(texIndirizzo.getText(), "VARCHAR");
                    sql += " ,intestazione_riga3 = " + Db.pc(texCap.getText() + " " + texLocalita.getText() + " (" + texProv.getText() + ")", "VARCHAR");
                    sql += " ,intestazione_riga4 = " + Db.pc("Tel. " + texTelefono.getText() + " / Fax " + texFax.getText(), "VARCHAR");
                    if (texWeb.getText().length() > 0) {
                        if (texEmail.getText().length() > 0) {
                            sql += " ,intestazione_riga5 = " + Db.pc(texWeb.getText() + " / " + texEmail.getText(), "VARCHAR");
                        } else {
                            sql += " ,intestazione_riga5 = " + Db.pc(texWeb.getText(), "VARCHAR");
                        }
                    }
                    if (texPartitaIva.getText().length() > 0) {
                        if (texCodiceFiscale.getText().length() > 0) {
                            sql += " ,intestazione_riga6 = " + Db.pc("P.IVA " + texPartitaIva.getText() + " - Cod. Fiscale " + texCodiceFiscale.getText(), "VARCHAR");
                        } else {
                            sql += " ,intestazione_riga6 = " + Db.pc("P.IVA " + texPartitaIva.getText(), "VARCHAR");
                        }
                    }
                    Db.executeSql(sql);
                } catch (Exception err) {
                    err.printStackTrace();
                }            
            }
            
            dispose();
        }
    }//GEN-LAST:event_butConfermaActionPerformed

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered

    }//GEN-LAST:event_jLabel13MouseEntered

    private void registraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraActionPerformed
        main.fileIni.setValue("varie", "dati_azienda_registra_invoicex", registra.isSelected());
    }//GEN-LAST:event_registraActionPerformed
    
    private void leggiDatiDaDb() {
        ResultSet r = Db.openResultSet("select " + main.campiDatiAzienda + " from dati_azienda");
        try {
            r.next();
            texRagioneSociale.setText(r.getString("ragione_sociale"));
            texPartitaIva.setText(r.getString("piva"));
            texCodiceFiscale.setText(r.getString("cfiscale"));
            texIndirizzo.setText(r.getString("indirizzo"));
            texCap.setText(r.getString("cap"));
            texLocalita.setText(r.getString("localita"));
            texProv.setText(r.getString("provincia"));
            texTelefono.setText(r.getString("telefono"));
            texFax.setText(r.getString("fax"));
            texWeb.setText(r.getString("sito_web"));
            texEmail.setText(r.getString("email"));
        } catch (Exception err) {
            err.printStackTrace();
        }
    }
    
    private void scriviDatiSuDb() {
        try {
            Map m = new HashMap();
            m.put("ragione_sociale", texRagioneSociale.getText());
            m.put("piva", texPartitaIva.getText());
            m.put("cfiscale", texCodiceFiscale.getText());
            m.put("indirizzo", texIndirizzo.getText());
            m.put("cap", texCap.getText());
            m.put("localita", texLocalita.getText());
            m.put("provincia", texProv.getText());
            m.put("telefono", texTelefono.getText());
            m.put("fax", texFax.getText());
            m.put("sito_web", texWeb.getText());
            m.put("email", texEmail.getText());
            m.put("flag_dati_inseriti", "S");
            String sql = "update dati_azienda set " + DbUtils.prepareSqlFromMap(m);
            DbUtils.tryExecQuery(Db.getConn(), sql);
        } catch (Exception err) {
            err.printStackTrace();
            SwingUtils.showExceptionMessage(main.getPadreFrame(), err);
        }        
    }
    
    boolean controllaDati() {
        if (texRagioneSociale.getText().length() == 0) {
            texRagioneSociale.requestFocus();
            JOptionPane.showMessageDialog(this, "La ragione sociale non è inserita", "Attenzione", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (texRagioneSociale.getText().length() <= 3) {
            texRagioneSociale.requestFocus();
            JOptionPane.showMessageDialog(this, "La ragione sociale è troppo breve", "Attenzione", JOptionPane.INFORMATION_MESSAGE);
            return false;            
        }
        if (texPartitaIva.getText().length() == 0) {
            texPartitaIva.requestFocus();
            JOptionPane.showMessageDialog(this, "La partita iva non è inserita", "Attenzione", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }        
        if (texPartitaIva.getText().length() < 11) {
            texPartitaIva.requestFocus();
            JOptionPane.showMessageDialog(this, "La partita iva è troppo breve", "Attenzione", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDialogDatiAzienda(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAnnulla;
    private javax.swing.JButton butConferma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox registra;
    private javax.swing.JTextField texCap;
    private javax.swing.JTextField texCodiceFiscale;
    private javax.swing.JTextField texEmail;
    private javax.swing.JTextField texFax;
    private javax.swing.JTextField texIndirizzo;
    private javax.swing.JTextField texLocalita;
    private javax.swing.JTextField texPartitaIva;
    private javax.swing.JTextField texProv;
    private javax.swing.JTextField texRagioneSociale;
    private javax.swing.JTextField texTelefono;
    private javax.swing.JTextField texWeb;
    // End of variables declaration//GEN-END:variables
    
}
