/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameIntro2.java
 *
 * Created on 20-ott-2011, 10.13.00
 */

package it.tnx.invoicex.gui;

import gestioneFatture.MenuPanel;
import gestioneFatture.main;
import it.tnx.commons.DateUtils;
import it.tnx.commons.HttpUtils;
import it.tnx.invoicex.Main;
import it.tnx.invoicex.PlatformUtils;
import java.io.File;
import javax.swing.ImageIcon;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author mceccarelli
 */
public class JFrameIntro2 extends javax.swing.JFrame {

    /** Creates new form JFrameIntro2 */
    public JFrameIntro2() {
        initComponents();

        try {
            File logover = new File("img/logover.png");
            if (logover.exists()) {
                labLogo.setIcon(new javax.swing.ImageIcon(logover.getAbsolutePath()));
            } else {
                labLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/tnx/invoicex/res/logo.jpg")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            setIconImage(main.getLogoIcon());
        } catch (Exception err) {
            err.printStackTrace();
        }

        labVer.setText(main.version.toString() + " (" + MenuPanel.getBuildH(main.build) + ")");
        labVer1.setText(StringUtils.replace(labVer1.getText(), "#anno#", String.valueOf(DateUtils.getCurrentYear())));

        if (PlatformUtils.isLinux()) {
            labVer1.setFont(labVer1.getFont().deriveFont(labVer1.getFont().getSize() - 2f));
            labVer.setFont(labVer.getFont().deriveFont(labVer.getFont().getSize() - 2f));
            labMess.setFont(labMess.getFont().deriveFont(labMess.getFont().getSize() - 2f));
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        labMess = new javax.swing.JLabel();
        labVer = new javax.swing.JLabel();
        labVer1 = new javax.swing.JLabel();
        labLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invoicex - caricamento in corso");
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setFocusable(false);
        jProgressBar1.setRequestFocusEnabled(false);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 150, 16));

        labMess.setFont(labMess.getFont().deriveFont((labMess.getFont().getStyle() | java.awt.Font.ITALIC)));
        labMess.setForeground(new java.awt.Color(255, 255, 255));
        labMess.setText("...");
        getContentPane().add(labMess, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 168, 475, 25));

        labVer.setFont(labVer.getFont());
        labVer.setForeground(new java.awt.Color(255, 255, 255));
        labVer.setText("versione");
        labVer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(labVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 440, 25));

        labVer1.setFont(labVer1.getFont());
        labVer1.setForeground(new java.awt.Color(255, 255, 255));
        labVer1.setText("<html> Invoicex è un programma di <b>TNX</b> / www.tnx.it / www.invoicex.it<br> Copyright © #anno# by <b>TNX</b> / Tutti i diritti riservati </html>");
        getContentPane().add(labVer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 185, 440, 50));

        labLogo.setBackground(new java.awt.Color(51, 255, 51));
        labLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(labLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameIntro2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JLabel labLogo;
    public javax.swing.JLabel labMess;
    public javax.swing.JLabel labVer;
    public javax.swing.JLabel labVer1;
    // End of variables declaration//GEN-END:variables

    public void setLogo() {
        try {
            if (!Main.applet) {
//                this.labLogo.setIcon(new ImageIcon(new java.net.URL("file:" + main.homeDir + "img/logo.gif")));
//                java.io.File f = new java.io.File(main.homeDir + "img/logo.jpg");
//                if (f.exists()) this.labLogo.setIcon(new ImageIcon(new java.net.URL("file:" + main.homeDir + "img/logo.jpg")));
//                labLogo.setIcon(new ImageIcon(getClass().getResource("/it/tnx/invoicex/res/logo.jpg")));
            } else {
                File filelogo = new File(main.wd + "img/logo.jpg");
                if (!filelogo.exists()) {
                    filelogo.getParentFile().mkdirs();
                    HttpUtils.saveFile("http://www.tnx.dyndns.org/download/cl_test/run/img/logo.jpg", filelogo.getAbsolutePath());
                }
                java.net.URL urllogo = new java.net.URL("file:" + filelogo.getAbsolutePath());
                System.out.println("urllogo = " + urllogo);
                this.labLogo.setIcon(new ImageIcon(urllogo));
            }
        } catch (Exception err) {
            javax.swing.JOptionPane.showMessageDialog(null, err);
        }
    }
}
