/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPackHeaderRenderer.java
 *
 * Created on 4-giu-2012, 16.22.23
 */

package it.tnx.invoicex.gui;

import javax.swing.JFrame;
import javax.swing.SwingConstants;
import javax.swing.UIManager;

/**
 *
 * @author mceccarelli3
 */
public class PanelPackHeaderRenderer extends javax.swing.JPanel {

    /** Creates new form PanelPackHeaderRenderer */
    public PanelPackHeaderRenderer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jideLabel5 = new com.jidesoft.swing.JideLabel();
        jideLabel6 = new com.jidesoft.swing.JideLabel();
        jideLabel7 = new com.jidesoft.swing.JideLabel();
        jideLabel8 = new com.jidesoft.swing.JideLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jideLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jideLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/tnx/invoicex/res/plugins/base.png"))); // NOI18N
        jPanel2.add(jideLabel5);

        jideLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jideLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/tnx/invoicex/res/plugins/pro.png"))); // NOI18N
        jPanel2.add(jideLabel6);

        jideLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jideLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/tnx/invoicex/res/plugins/proplus.png"))); // NOI18N
        jPanel2.add(jideLabel7);

        jideLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jideLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/tnx/invoicex/res/plugins/ent.png"))); // NOI18N
        jideLabel8.setClockwise(false);
        jPanel2.add(jideLabel8);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private com.jidesoft.swing.JideLabel jideLabel5;
    private com.jidesoft.swing.JideLabel jideLabel6;
    private com.jidesoft.swing.JideLabel jideLabel7;
    private com.jidesoft.swing.JideLabel jideLabel8;
    // End of variables declaration//GEN-END:variables


    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
        }
        JFrame f = new JFrame("test");
        f.getContentPane().add(new PanelPackHeaderRenderer());
        f.pack();
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }
}
