/*
 * JDialogDatePicker.java
 *
 * Created on July 12, 2004, 3:50 PM
 */

package it.tnx.gui;

import javax.swing.*;
/**
 *
 * @author  marco
 */
public class JDialogDatePicker extends javax.swing.JDialog {
  boolean flagAnnulla = false;

  /** Creates new form JDialogDatePicker */
  public JDialogDatePicker() {
    super();
    initComponents();
    //this.calCalendar.setLocale(java.util.Locale.ITALY);
  }

  public JDialogDatePicker(JFrame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    //this.calCalendar.setLocale(java.util.Locale.ITALY);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    //calCalendar = new com.toedter.calendar.JCalendar();

    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        exitForm(evt);
      }
    });

    getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

    jButton1.setText("Annulla");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jPanel2.add(jButton1);

    jButton2.setText("Conferma");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jPanel2.add(jButton2);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    /*calCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        calCalendarMouseClicked(evt);
      }
    });
    calCalendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        calCalendarPropertyChange(evt);
      }
    });

    jPanel3.add(calCalendar);
     */

    getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

    pack();
  }

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    this.flagAnnulla = true;
    this.dispose();
  }

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    this.flagAnnulla = false;
    this.dispose();
  }

  private void calCalendarMouseClicked(java.awt.event.MouseEvent evt) {
    System.out.println(this.getComponentAt(evt.getPoint()));
  }

  private void calCalendarPropertyChange(java.beans.PropertyChangeEvent evt) {
    //System.out.println(evt.getPropertyName() + ":" + evt.getNewValue());
  }

  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {
    //System.exit(0);
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    new JDialogDatePicker().show();
  }

  // Variables declaration - do not modify
  //private com.toedter.calendar.JCalendar calCalendar;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  // End of variables declaration


  public java.util.Date getDate() {
    if (this.flagAnnulla == true) return null;
    return null;
    //return this.calCalendar.getCalendar().getTime();
  }
} 