/*
 * JTableEditing.java
 *
 * Created on 18 agosto 2005, 10.34
 */

package it.tnx.gui;

import java.awt.AWTEvent;
import java.awt.Component;
import java.awt.EventQueue;
import java.awt.KeyboardFocusManager;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  marco
 */
public class JTableEditing extends javax.swing.JFrame {
    
    /** Creates new form JTableEditing */
    public JTableEditing() {
        initComponents();
        
        table.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        
        JTextField tf = new JTextField();
        tf.setBorder(BorderFactory.createEmptyBorder());
        table.setDefaultEditor(Object.class, new DefaultCellEditor(tf));
        
        /*JComboBox combo = new JComboBox(new String[]{"item1", "item2", "item3"});
        combo.setBorder(BorderFactory.createEmptyBorder());
        table.getColumn("B").setCellEditor(new DefaultCellEditor(combo));
         */
        
        JComboBox combo = new JComboBox(new String[]{"item1", "item2", "item3"}){
            public void processFocusEvent(FocusEvent fe) {
                super.processFocusEvent(fe);
                Component focusOwner = KeyboardFocusManager.
                        getCurrentKeyboardFocusManager().getFocusOwner();
                
                if (isDisplayable() && fe.getID()==FocusEvent.FOCUS_GAINED
                        && focusOwner==this && !isPopupVisible()) {
                    showPopup();
                }
            }
        };
        combo.setBorder(BorderFactory.createEmptyBorder());
        table.getColumn("Title 2").setCellEditor(new DefaultCellEditor(combo));
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new JTable(2, 2){
            private final KeyStroke tabKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_TAB, 0);
            public void changeSelection(int rowIndex, int columnIndex, boolean toggle, boolean extend) {
                AWTEvent currentEvent = EventQueue.getCurrentEvent();
                if(currentEvent instanceof KeyEvent){
                    KeyEvent ke = (KeyEvent)currentEvent;
                    if(ke.getSource()!=this)
                    return;
                    // focus change with keyboard
                    if(rowIndex==0 && columnIndex==0
                        && KeyStroke.getKeyStrokeForEvent(ke).equals(tabKeyStroke)){
                        ((DefaultTableModel)getModel()).addRow(new Object[getColumnCount()]);
                        rowIndex = getRowCount()-1;
                    }
                }
                super.changeSelection(rowIndex, columnIndex, toggle, extend);
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception err) {
            err.printStackTrace();
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTableEditing().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    
}
