/**
 * Invoicex
 * Copyright (c) 2005,2006,2007 Marco Ceccarelli, Tnx snc
 *
 * Questo software è soggetto, e deve essere distribuito con la licenza  
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 * 
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */


package it.tnx.dbeans;

import java.sql.*;
import java.util.*;
/**
 *
 * @author  marco ceccarelli
 */
public class JDbComboTextList extends javax.swing.JPanel {
  private Vector dbItems = new Vector();
  private Vector dbItemsK = new Vector();
  private String currentKey = null;
  
  private String dbNomeCampo;
  private String dbTipoCampo;
  private String dbDescCampo;
  private boolean locked = false;
  private boolean refresh = true;
  private boolean saveChanges = true;
  public boolean dbModificato = false;
  private boolean findWhileWriting = false;  
  
  javax.swing.DefaultListModel model = new javax.swing.DefaultListModel();
  
  /** Creates new form JDbComboTextList */
  public JDbComboTextList() {
    initComponents();
    this.lisItems.setVisible(false);
    this.lisItems.setModel(model);
  }
  
  public void openList(ResultSet resu) {
    dbItems = new Vector();
    dbItemsK = new Vector();
    try {
      while (resu.next()) {
        model.addElement(resu.getString(1));
        dbItems.addElement(resu.getString(1));
        dbItemsK.addElement(resu.getString(2));
      }
    } catch (java.sql.SQLException sqlex) {}
  }
  
  public String getText() {
    return this.texFind.getText();
  }
  
  public String getKey() {
    return this.currentKey;
  }
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    texFind = new javax.swing.JTextField();
    lisItems = new javax.swing.JList();

    setLayout(new java.awt.BorderLayout());

    texFind.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        texFindKeyTyped(evt);
      }
    });

    add(texFind, java.awt.BorderLayout.NORTH);

    lisItems.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lisItemsMouseClicked(evt);
      }
    });

    add(lisItems, java.awt.BorderLayout.CENTER);

  }//GEN-END:initComponents

  private void lisItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lisItemsMouseClicked
    this.currentKey = String.valueOf(dbItemsK.elementAt(this.lisItems.getSelectedIndex()));
    this.texFind.setText(String.valueOf(dbItems.elementAt(this.lisItems.getSelectedIndex())));
  }//GEN-LAST:event_lisItemsMouseClicked

  private void texFindKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texFindKeyTyped
    this.currentKey = null;
    if (this.lisItems.isVisible() == false) {
      super.setSize(super.getWidth(), 200);
      lisItems.setVisible(true);
    }
  }//GEN-LAST:event_texFindKeyTyped
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField texFind;
  private javax.swing.JList lisItems;
  // End of variables declaration//GEN-END:variables
  
}
