/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogMessage.java
 *
 * Created on 6-giu-2012, 10.30.44
 */

package it.tnx;

import java.awt.Dialog;
import javax.swing.JButton;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author mceccarelli3
 */
public class JDialogMessage extends javax.swing.JDialog {

    /** Creates new form JDialogMessage */
    public JDialogMessage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDialogMessage(Dialog owner, boolean modal) {
        super(owner, modal);
        initComponents();
    }

    public JTextArea getTextArea() {
        return this.texMessage;
    }

    public JButton getPulsanteChiudi() {
        return this.butChiudi;
    }

    public JProgressBar getAvanzamento() {
        return this.proAvanzamento;
    }

    public JScrollPane getTextAreaScrollPane() {
        return this.scrTextArea;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrTextArea = new javax.swing.JScrollPane();
        texMessage = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        proAvanzamento = new javax.swing.JProgressBar();
        panbasso = new javax.swing.JPanel();
        butChiudi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        texMessage.setEditable(false);
        scrTextArea.setViewportView(texMessage);

        jPanel1.add(scrTextArea, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(proAvanzamento);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        butChiudi.setText("Chiudi");
        butChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butChiudiActionPerformed(evt);
            }
        });
        panbasso.add(butChiudi);

        getContentPane().add(panbasso, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butChiudiActionPerformed
        this.dispose();
}//GEN-LAST:event_butChiudiActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogMessage dialog = new JDialogMessage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butChiudi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel panbasso;
    private javax.swing.JProgressBar proAvanzamento;
    private javax.swing.JScrollPane scrTextArea;
    private javax.swing.JTextArea texMessage;
    // End of variables declaration//GEN-END:variables

}
