/**
 * Invoicex
 * Copyright (c) 2005,2006,2007 Marco Ceccarelli, Tnx snc
 *
 * Questo software è soggetto, e deve essere distribuito con la licenza  
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 * 
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */
package gestioneFatture;

import it.tnx.Db;

public class diaDistRibaTracciato
        extends javax.swing.JDialog {

    public boolean cancel = false;
    public CoordinateBancarie coord;
    public boolean prova = true;
    public String nomeFile = "riba.txt";
    public String codSia = "";
    public String codSiaCred = "";
    public String supporto = "";
    public String freeText = "";
    public String numAuth = "";
    public String provAuth = "";
    public String dataAuth = "";
    public String data_distinta = Db.getCurrDateTimeMysql();

    /** Creates new form diaDistRiba */
    public diaDistRibaTracciato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //carico la griglia dei conti
        griBanc.dbNomeTabella = "";
        griBanc.flagUsaThread = false;

        java.util.Hashtable colsWidthPerc = new java.util.Hashtable();
        colsWidthPerc.put("abi", new Double(8));
        colsWidthPerc.put("nome", new Double(15));
        colsWidthPerc.put("cab", new Double(8));
        colsWidthPerc.put("comune", new Double(15));
        colsWidthPerc.put("indirizzo", new Double(20));
        colsWidthPerc.put("cc", new Double(15));
        colsWidthPerc.put("note", new Double(15));
        griBanc.columnsSizePerc = colsWidthPerc;

        String sql = "select";
        sql += " dati_azienda_banche.abi";
        sql += " ,banche_abi.nome";
        sql += " ,dati_azienda_banche.cab";
        sql += " ,comuni.comune";
        sql += " ,banche_cab.indirizzo";
        sql += " ,dati_azienda_banche.cc";
        sql += " ,dati_azienda_banche.note";
        sql += " from dati_azienda_banche left join banche_abi on dati_azienda_banche.abi = banche_abi.abi";
        sql += " left join banche_cab on dati_azienda_banche.cab = banche_cab.cab and dati_azienda_banche.abi = banche_cab.abi";
        sql += " left join comuni on banche_cab.codice_comune = comuni.codice";
        this.griBanc.dbOpen(Db.getConn(), sql);
    }

    /** This method is called from within the constructor to

     * initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is

     * always regenerated by the Form Editor.

     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panBanc = new tnxbeans.tnxDbPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        griBanc = new tnxbeans.tnxDbGrid();
        jLabel1 = new javax.swing.JLabel();
        butCrea = new javax.swing.JButton();
        butAnnu = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        texSia = new javax.swing.JTextField();
        texSupporto4 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        texFreeText4 = new javax.swing.JTextField();
        texSiaCred4 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        texSia5 = new javax.swing.JTextField();
        texSupporto5 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        texFreeText5 = new javax.swing.JTextField();
        texSiaCred5 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        texSia6 = new javax.swing.JTextField();
        texSupporto6 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        texFreeText6 = new javax.swing.JTextField();
        texSiaCred6 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        texSia7 = new javax.swing.JTextField();
        texSupporto7 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        texFreeText7 = new javax.swing.JTextField();
        texSiaCred7 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panBanc.setPreferredSize(new java.awt.Dimension(50, 50));
        panBanc.setLayout(new java.awt.BorderLayout());

        griBanc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(griBanc);

        panBanc.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(panBanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 35, 625, 190));

        jLabel1.setText("Seleziona il conto di accredito");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        butCrea.setText("Crea");
        butCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCreaActionPerformed(evt);
            }
        });
        jPanel1.add(butCrea, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 70, -1));

        butAnnu.setText("Annulla");
        butAnnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnuActionPerformed(evt);
            }
        });
        jPanel1.add(butAnnu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 70, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Supporto:");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 20));
        jPanel6.add(texSia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 190, -1));
        jPanel6.add(texSupporto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 190, -1));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Codice SIA Azienda Mittente:");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 20));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Campo Libero:");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 20));

        texFreeText4.setMinimumSize(new java.awt.Dimension(100, 20));
        texFreeText4.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel6.add(texFreeText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 190, 20));
        jPanel6.add(texSiaCred4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 190, -1));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Codice SIA Azienda Creditrice:");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 20));

        jLabel26.setText("Dati Generali");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Supporto:");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 20));
        jPanel7.add(texSia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 190, -1));
        jPanel7.add(texSupporto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 190, -1));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Codice SIA Azienda Mittente:");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 20));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Campo Libero:");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 20));

        texFreeText5.setMinimumSize(new java.awt.Dimension(100, 20));
        texFreeText5.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel7.add(texFreeText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 190, 20));
        jPanel7.add(texSiaCred5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 190, -1));

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Codice SIA Azienda Creditrice:");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 20));

        jLabel31.setText("Dati Generali");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 390, 140));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Supporto:");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 20));
        jPanel8.add(texSia6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 190, -1));
        jPanel8.add(texSupporto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 190, -1));

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Codice SIA Azienda Mittente:");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 20));

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("Campo Libero:");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 20));

        texFreeText6.setMinimumSize(new java.awt.Dimension(100, 20));
        texFreeText6.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel8.add(texFreeText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 190, 20));
        jPanel8.add(texSiaCred6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 190, -1));

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("Codice SIA Azienda Creditrice:");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 20));

        jLabel36.setText("Dati Generali");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Supporto:");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 20));
        jPanel9.add(texSia7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 190, -1));
        jPanel9.add(texSupporto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 190, -1));

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Codice SIA Azienda Mittente:");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 20));

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("Campo Libero:");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 20));

        texFreeText7.setMinimumSize(new java.awt.Dimension(100, 20));
        texFreeText7.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel9.add(texFreeText7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 190, 20));
        jPanel9.add(texSiaCred7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 190, -1));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("Codice SIA Azienda Creditrice:");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 20));

        jLabel41.setText("Dati Generali");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 390, 140));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 390, 140));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 390, 140));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void butAnnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnuActionPerformed
        this.cancel = true;
        this.hide();
}//GEN-LAST:event_butAnnuActionPerformed

    private void butCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCreaActionPerformed
        this.coord = new CoordinateBancarie();

        String temp;
        temp = String.valueOf(griBanc.getValueAt(griBanc.getSelectedRow(), 0));
        this.coord.setAbi(temp);
        temp = String.valueOf(griBanc.getValueAt(griBanc.getSelectedRow(), 2));
        this.coord.setCab(temp);
        temp = String.valueOf(griBanc.getValueAt(griBanc.getSelectedRow(), 5));
        this.coord.setCc(temp);

        codSia = texSia.getText();
        if(codSia.length() != 5){
            javax.swing.JOptionPane.showMessageDialog(this, "Codice Sia non corretto, deve essere di 5 caratteri");
            return;
        }

        codSiaCred = texSiaCred4.getText();
        if(codSiaCred.length() != 5){
            javax.swing.JOptionPane.showMessageDialog(this, "Codice Sia non corretto, deve essere di 5 caratteri");
            return;
        }

        supporto = texSupporto4.getText();
        if(supporto.length() > 20){
            javax.swing.JOptionPane.showMessageDialog(this, "Supporto non corretto, deve essere di massimo 20 caratteri");
            return;
        } else {
            for(int i = 0; i < 20-supporto.length(); i++){
                supporto += " ";
            }
        }

        freeText = texFreeText4.getText();
        if(freeText.length() > 5){
            javax.swing.JOptionPane.showMessageDialog(this, "Supporto non corretto, deve essere di massimo 20 caratteri");
            return;
        } else {
            for(int i = 0; i < 5-freeText.length(); i++){
                freeText += " ";
            }
        }
        
        this.dispose();
    }//GEN-LAST:event_butCreaActionPerformed

    /**

     * @param args the command line arguments

     */
    public static void main(String[] args) {
        new diaDistRibaTracciato(new javax.swing.JFrame(), true).show();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAnnu;
    private javax.swing.JButton butCrea;
    private javax.swing.ButtonGroup buttonGroup1;
    private tnxbeans.tnxDbGrid griBanc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private tnxbeans.tnxDbPanel panBanc;
    private javax.swing.JTextField texFreeText4;
    private javax.swing.JTextField texFreeText5;
    private javax.swing.JTextField texFreeText6;
    private javax.swing.JTextField texFreeText7;
    private javax.swing.JTextField texSia;
    private javax.swing.JTextField texSia5;
    private javax.swing.JTextField texSia6;
    private javax.swing.JTextField texSia7;
    private javax.swing.JTextField texSiaCred4;
    private javax.swing.JTextField texSiaCred5;
    private javax.swing.JTextField texSiaCred6;
    private javax.swing.JTextField texSiaCred7;
    private javax.swing.JTextField texSupporto4;
    private javax.swing.JTextField texSupporto5;
    private javax.swing.JTextField texSupporto6;
    private javax.swing.JTextField texSupporto7;
    // End of variables declaration//GEN-END:variables
}
