/**
 * Invoicex
 * Copyright (c) 2005,2006,2007 Marco Ceccarelli, Tnx snc
 *
 * Questo software è soggetto, e deve essere distribuito con la licenza  
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 * 
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */



package gestioneFatture;

import it.tnx.Db;
import java.text.*;

import java.util.*;

public class diaDataDistinta
    extends javax.swing.JDialog {

    public int intero;

    /** Creates new form diaDataDistinta */
    public diaDataDistinta(javax.swing.JFrame parent, boolean modal, int codice_distinta) {
        super(parent, modal);
        this.intero = codice_distinta;
        initComponents();

        java.text.SimpleDateFormat formattazione_init = new java.text.SimpleDateFormat("dd/MM/yy");
        this.texData.setText(formattazione_init.format(new java.util.Date()));
    }

    /** This method is called from within the constructor to

     * initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is

     * always regenerated by the Form Editor.

     */
    private void initComponents() {//GEN-BEGIN:initComponents
        texData = new tnxbeans.tnxTextField();
        butCont = new javax.swing.JButton();
        getContentPane().setLayout(new java.awt.FlowLayout());
        setTitle("Seleziona la data della distinta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        texData.setDbRiempire(false);
        texData.setDbSalvare(false);
        texData.setDbTipoCampo("");
        texData.setMinimumSize(new java.awt.Dimension(100, 20));
        texData.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(texData);
        butCont.setText("Conferma");
        butCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butContActionPerformed(evt);
            }
        });
        getContentPane().add(butCont);
        pack();
    }//GEN-END:initComponents

    private void butContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butContActionPerformed

        // Add your handling code here:
        try {

            DateFormat parsaData = new SimpleDateFormat("dd/MM/yy");
            Date data_inserita = parsaData.parse(this.texData.getText());
            java.text.SimpleDateFormat riformattazione = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String nuova_data = riformattazione.format(data_inserita);
            String sql = "update distinte_riba set data = '" + nuova_data + "' where id = '" + String.valueOf(intero) + "';";
            Db.executeSql(sql);
        } catch (Exception err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_butContActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**

     * @param args the command line arguments

     */
    public static void main(String[] args) {

        //new diaDataDistinta(new javax.swing.JFrame(), true).show();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCont;
    private tnxbeans.tnxTextField texData;

    // End of variables declaration//GEN-END:variables
}
