/**
 * Invoicex
 * Copyright (c) 2005,2006,2007 Marco Ceccarelli, Tnx snc
 *
 * Questo software è soggetto, e deve essere distribuito con la licenza  
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 * 
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */



package gestioneFatture;
import it.tnx.Db;
import it.tnx.accessoUtenti.Permesso;
import it.tnx.commons.SwingUtils;
import java.awt.Dimension;
import java.sql.Types;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import tnxbeans.DbEvent;
import tnxbeans.DbListener;

public class frmArti
    extends javax.swing.JInternalFrame {

    /** Creates new form frmDati_blank */
    public frmArti() {
        initComponents();

        if (main.getPersonal().equals(main.PERSONAL_GIANNI)) {
            this.labPrez1.setText("prezzo Rivenditori");
            this.labPrez2.setText("prezzo Utilizzatori");
        }

        iva.dbOpenList(Db.getConn(), "select CAST(CONCAT(codice, ' - ', descrizione, ' (', percentuale, '%)') AS CHAR(100)) as descrizione, codice from codici_iva order by codice");

        //associo il panel ai dati
        this.dati.dbNomeTabella = "articoli";

        Vector chiave = new Vector();
        chiave.add("codice");
        this.dati.dbChiave = chiave;
        this.dati.butSave = this.butSave;
        this.dati.butUndo = this.butUndo;
        this.dati.butNew = this.butNew;
        this.dati.butDele = this.butDele;
        this.dati.tipo_permesso = Permesso.PERMESSO_ANAGRAFICA_ARTICOLI;
        this.dati.dbOpen(Db.getConn(), "select * from articoli");
        this.dati.dbRefresh();

        //apro la griglia
        this.griglia.dbChiave = chiave;

        String sql;
        sql = "select ";
        sql += " codice, ";
        sql += " descrizione, ";
        sql += " um , ";
        sql += " prezzo1, ";
        sql += " prezzo2, ";
        sql += " iva ";
        sql += " from articoli";
        sql += " order by codice";
        this.griglia.dbEditabile = false;
        this.griglia.flagUsaThread = false;
//        this.griglia.flagUsaOrdinamento = true;

        java.util.Hashtable colsWidthPerc = new java.util.Hashtable();
        colsWidthPerc.put("codice", new Double(10));
        colsWidthPerc.put("descrizione", new Double(30));
        colsWidthPerc.put("um", new Double(5));
        colsWidthPerc.put("prezzo1", new Double(20));
        colsWidthPerc.put("prezzo2", new Double(20));
        colsWidthPerc.put("iva", new Double(10));
        griglia.columnsSizePerc = colsWidthPerc;

        this.griglia.dbOpen(Db.getConn(), sql);
        this.griglia.dbPanel = this.dati;
        this.dati.dbRefresh();

        this.dati.addDbListener(new DbListener() {

            public void statusFired(DbEvent event) {
                if (event.getStatus() == dati.STATUS_REFRESHING || event.getStatus() == dati.STATUS_ADDING) {
                    if (frmArti.this.texTipo.getText().equals("A")) {
                        frmArti.this.grpSel.setSelected(frmArti.this.rbtAcq.getModel(), true);
                    } else if (frmArti.this.texTipo.getText().equals("V")) {
                        frmArti.this.grpSel.setSelected(frmArti.this.rbtVen.getModel(), true);
                    } else {
                        frmArti.this.grpSel.setSelected(frmArti.this.rbtEnt.getModel(), true);
                    }
                }
            }
        });
    }

    /** This method is called from within the constructor to

   * initialize the form.

   * WARNING: Do NOT modify this code. The content of this method is

   * always regenerated by the Form Editor.

   */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSel = new javax.swing.ButtonGroup();
        panAlto = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        butNew = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        butDele = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        butFind = new javax.swing.JButton();
        jLabel131 = new javax.swing.JLabel();
        butFirs = new javax.swing.JButton();
        butPrev = new javax.swing.JButton();
        butNext = new javax.swing.JButton();
        butLast = new javax.swing.JButton();
        jLabel132 = new javax.swing.JLabel();
        butStampaElenco = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jLabel4 = new javax.swing.JLabel();
        texSearch = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        tabCent = new javax.swing.JTabbedPane();
        panDati = new javax.swing.JPanel();
        dati = new tnxbeans.tnxDbPanel();
        texUm = new tnxbeans.tnxTextField();
        texCodi = new tnxbeans.tnxTextField();
        texDesc = new tnxbeans.tnxTextField();
        texPrez = new tnxbeans.tnxTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        labPrez1 = new javax.swing.JLabel();
        jLabel231 = new javax.swing.JLabel();
        labPrez2 = new javax.swing.JLabel();
        texPrez1 = new tnxbeans.tnxTextField();
        jLabel3 = new javax.swing.JLabel();
        texUm1 = new tnxbeans.tnxTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbtAcq = new javax.swing.JRadioButton();
        rbtVen = new javax.swing.JRadioButton();
        rbtEnt = new javax.swing.JRadioButton();
        texTipo = new tnxbeans.tnxTextField();
        iva = new tnxbeans.tnxComboField();
        panElen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        griglia = new tnxbeans.tnxDbGrid();
        jPanel1 = new javax.swing.JPanel();
        butUndo = new javax.swing.JButton();
        butSave = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Articoli");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panAlto.setLayout(new java.awt.BorderLayout());

        butNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/document-new.png"))); // NOI18N
        butNew.setText("Nuovo");
        butNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNewActionPerformed(evt);
            }
        });
        jToolBar1.add(butNew);

        jLabel1.setText(" ");
        jToolBar1.add(jLabel1);

        butDele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/places/user-trash.png"))); // NOI18N
        butDele.setText("Elimina");
        butDele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeleActionPerformed(evt);
            }
        });
        jToolBar1.add(butDele);

        jLabel11.setText(" ");
        jToolBar1.add(jLabel11);

        jLabel12.setText(" ");
        jToolBar1.add(jLabel12);

        jLabel13.setText(" ");
        jToolBar1.add(jLabel13);

        butFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/edit-find.png"))); // NOI18N
        butFind.setText("Trova");
        butFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFindActionPerformed(evt);
            }
        });
        jToolBar1.add(butFind);

        jLabel131.setText(" ");
        jToolBar1.add(jLabel131);

        butFirs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/go-first.png"))); // NOI18N
        butFirs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFirsActionPerformed(evt);
            }
        });
        jToolBar1.add(butFirs);

        butPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/go-previous.png"))); // NOI18N
        butPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPrevActionPerformed(evt);
            }
        });
        jToolBar1.add(butPrev);

        butNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/go-next.png"))); // NOI18N
        butNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNextActionPerformed(evt);
            }
        });
        jToolBar1.add(butNext);

        butLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/go-last.png"))); // NOI18N
        butLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLastActionPerformed(evt);
            }
        });
        jToolBar1.add(butLast);

        jLabel132.setText(" ");
        jToolBar1.add(jLabel132);

        butStampaElenco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/document-print.png"))); // NOI18N
        butStampaElenco.setText("Stampa elenco");
        butStampaElenco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butStampaElencoActionPerformed(evt);
            }
        });
        jToolBar1.add(butStampaElenco);

        panAlto.add(jToolBar1, java.awt.BorderLayout.CENTER);

        jToolBar3.setRollover(true);

        jLabel4.setText(" Cerca ");
        jToolBar3.add(jLabel4);

        texSearch.setMaximumSize(new java.awt.Dimension(250, 20));
        texSearch.setMinimumSize(new java.awt.Dimension(6, 5));
        texSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                texSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                texSearchKeyReleased(evt);
            }
        });
        jToolBar3.add(texSearch);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/edit-find.png"))); // NOI18N
        jButton3.setText("Mostra Tutti");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setMaximumSize(new java.awt.Dimension(90, 20));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton3);

        panAlto.add(jToolBar3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panAlto, java.awt.BorderLayout.NORTH);

        tabCent.setName("dati"); // NOI18N

        panDati.setName("dati"); // NOI18N
        panDati.setLayout(new java.awt.BorderLayout());

        dati.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texUm.setText("um");
        texUm.setDbDescCampo("");
        texUm.setDbNomeCampo("um");
        texUm.setDbTipoCampo("");
        texUm.setmaxChars(3);
        dati.add(texUm, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 65, 30, -1));

        texCodi.setText("codice");
        texCodi.setDbDescCampo("");
        texCodi.setDbNomeCampo("codice");
        texCodi.setDbTipoCampo("");
        texCodi.setmaxChars(20);
        dati.add(texCodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 130, -1));

        texDesc.setText("descrizione");
        texDesc.setDbDescCampo("");
        texDesc.setDbNomeCampo("descrizione");
        texDesc.setDbTipoCampo("");
        texDesc.setmaxChars(255);
        dati.add(texDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 365, -1));

        texPrez.setText("prezzo1");
        texPrez.setDbDescCampo("");
        texPrez.setDbNomeCampo("prezzo1");
        texPrez.setDbTipoCampo("valuta");
        texPrez.setmaxChars(12);
        dati.add(texPrez, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("unità di misura");
        dati.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 65, 105, 20));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("codice");
        dati.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 15, 100, -1));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("descrizione");
        dati.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 105, -1));

        labPrez1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labPrez1.setText("prezzo listino RIVENDITORI");
        dati.add(labPrez1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 90, 170, 20));

        jLabel231.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel231.setText("iva");
        dati.add(jLabel231, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 105, 20));

        labPrez2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labPrez2.setText("prezzo listino UTILIZZATORI");
        dati.add(labPrez2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 115, 170, 20));

        texPrez1.setText("prezzo2");
        texPrez1.setDbDescCampo("");
        texPrez1.setDbNomeCampo("prezzo2");
        texPrez1.setDbTipoCampo("valuta");
        texPrez1.setmaxChars(12);
        dati.add(texPrez1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 115, 90, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("peso");
        dati.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 15, 40, 20));

        texUm1.setText("kg");
        texUm1.setDbDescCampo("");
        texUm1.setDbNomeCampo("peso_kg");
        texUm1.setDbTipoCampo("decimal");
        texUm1.setmaxChars(15);
        dati.add(texUm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 15, 90, -1));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Kg");
        dati.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 15, 20, 20));

        jLabel8.setText("Tipologia Di Oggetto:");
        dati.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, 20));

        grpSel.add(rbtAcq);
        rbtAcq.setText("Acquisto");
        rbtAcq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAcqActionPerformed(evt);
            }
        });
        dati.add(rbtAcq, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        grpSel.add(rbtVen);
        rbtVen.setText("Vendita");
        rbtVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtVenActionPerformed(evt);
            }
        });
        dati.add(rbtVen, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        grpSel.add(rbtEnt);
        rbtEnt.setSelected(true);
        rbtEnt.setText("Entrambi");
        rbtEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEntActionPerformed(evt);
            }
        });
        dati.add(rbtEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        texTipo.setBackground(new java.awt.Color(255, 51, 51));
        texTipo.setText("tipo");
        texTipo.setDbNomeCampo("tipo");
        dati.add(texTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        iva.setEditable(false);
        iva.setDbDescCampo("");
        iva.setDbNomeCampo("iva");
        iva.setDbTipoCampo("");
        iva.setDbTrovaMentreScrive(true);
        iva.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                ivaPopupMenuWillBecomeVisible(evt);
            }
        });
        dati.add(iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 65, 170, -1));

        panDati.add(dati, java.awt.BorderLayout.CENTER);

        tabCent.addTab("dati", panDati);

        panElen.setName("elenco"); // NOI18N
        panElen.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(griglia);

        panElen.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabCent.addTab("elenco", panElen);

        getContentPane().add(tabCent, java.awt.BorderLayout.CENTER);

        butUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/edit-undo.png"))); // NOI18N
        butUndo.setText("Annulla");
        butUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUndoActionPerformed(evt);
            }
        });
        jPanel1.add(butUndo);

        butSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/devices/media-floppy.png"))); // NOI18N
        butSave.setText("Salva");
        butSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSaveActionPerformed(evt);
            }
        });
        jPanel1.add(butSave);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butStampaElencoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStampaElencoActionPerformed
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        int[] headerWidth = { 10, 50, 10, 10, 10, 10 };
        String nomeFilePdf = this.griglia.stampaTabella("Elenco Articoli", headerWidth);
        Util.start(nomeFilePdf);
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_butStampaElencoActionPerformed

    private void butLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLastActionPerformed

        // Add your handling code here:
        this.griglia.dbGoLast();
        if(this.texTipo.getText().equals("A")) {
            grpSel.setSelected(this.rbtAcq.getModel(), true);
        } else if(this.texTipo.getText().equals("V")) {
            grpSel.setSelected(this.rbtVen.getModel(), true);
        } else {
            grpSel.setSelected(this.rbtEnt.getModel(), true);
        }
    }//GEN-LAST:event_butLastActionPerformed

    private void butPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPrevActionPerformed

        // Add your handling code here:
        this.griglia.dbGoPrevious();
        if(this.texTipo.getText().equals("A")) {
            grpSel.setSelected(this.rbtAcq.getModel(), true);
        } else if(this.texTipo.getText().equals("V")) {
            grpSel.setSelected(this.rbtVen.getModel(), true);
        } else {
            grpSel.setSelected(this.rbtEnt.getModel(), true);
        }
    }//GEN-LAST:event_butPrevActionPerformed

    private void butFirsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFirsActionPerformed

        // Add your handling code here:
        this.griglia.dbGoFirst();
        if(this.texTipo.getText().equals("A")) {
            grpSel.setSelected(this.rbtAcq.getModel(), true);
        } else if(this.texTipo.getText().equals("V")) {
            grpSel.setSelected(this.rbtVen.getModel(), true);
        } else {
            grpSel.setSelected(this.rbtEnt.getModel(), true);
        }
    }//GEN-LAST:event_butFirsActionPerformed

    private void butNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNextActionPerformed

        // Add your handling code here:
        this.griglia.dbGoNext();
        if(this.texTipo.getText().equals("A")) {
            grpSel.setSelected(this.rbtAcq.getModel(), true);
        } else if(this.texTipo.getText().equals("V")) {
            grpSel.setSelected(this.rbtVen.getModel(), true);
        } else {
            grpSel.setSelected(this.rbtEnt.getModel(), true);
        }
    }//GEN-LAST:event_butNextActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        main.getPadre().closeFrame(this);
    }//GEN-LAST:event_formInternalFrameClosing

    private void butDeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeleActionPerformed

        int ret = JOptionPane.showConfirmDialog(this, "Sicuro di eliminare ?", "Attenzione", JOptionPane.YES_NO_OPTION);

        if (ret == JOptionPane.YES_OPTION) {

            String codiceArticolo = (String)dati.dbGetField("codice");
            this.dati.dbDelete();
            this.griglia.dbRefresh();

            //elimino i prezzi associati a questo articolo
            String sql = "delete from articoli_prezzi where articolo = " + Db.pc(codiceArticolo, java.sql.Types.VARCHAR);
            Db.executeSql(sql);
        }
    }//GEN-LAST:event_butDeleActionPerformed

    private void butFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFindActionPerformed

        boolean ret = this.griglia.dbFindNext();

        if (ret == false) {

            int ret2 = JOptionPane.showConfirmDialog(this, "Posizione non trovata\nVuoi riprovare dall'inizio ?", "Attenzione", JOptionPane.YES_NO_OPTION);

            //JOptionPane.showMessageDialog(this,"?-:"+String.valueOf(i));
            if (ret2 == JOptionPane.OK_OPTION) {

                boolean ret3 = this.griglia.dbFindFirst();
            }
        }
    }//GEN-LAST:event_butFindActionPerformed

    private void butUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUndoActionPerformed
        dati.dbUndo();
    }//GEN-LAST:event_butUndoActionPerformed

    private void butSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSaveActionPerformed
        this.dati.dbSave();
        this.griglia.dbRefresh();
    }//GEN-LAST:event_butSaveActionPerformed

    private void butNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNewActionPerformed
        this.dati.dbNew();

        //101 non + perch??? ??? stringa e non funzionerebbe

        /*
        
        java.sql.Statement stat;
        
        ResultSet resu;
        
        //apre il resultset per ultimo +1
        
        try {
        
          stat = Db.conn.createStatement();
        
          String sql = "select codice from articoli order by codice desc limit 1";
        
          resu = stat.executeQuery(sql);
        
          if(resu.next()==true) {
        
            this.texCodi.setText(String.valueOf(resu.getInt(1)+1));
        
          } else {
        
            this.texCodi.setText("1");
        
          }
        
        } catch (Exception err) {
        
          //javax.swing.JOptionPane.showMessageDialog(null,err.toString());
        
          this.texCodi.setText("");
        
        }
        
        */
        if (main.getPersonal().equals(main.PERSONAL_CUCINAIN)) {

            //metto 20% su iva
//            this.texIva.setText("10");
            iva.dbTrovaKey(10d);
        } else {

            //metto 20% su iva
//            this.texIva.setText("20");
            iva.dbTrovaKey(20d);
        }
    }//GEN-LAST:event_butNewActionPerformed

    private void rbtAcqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtAcqActionPerformed
        this.texTipo.setText("A");
}//GEN-LAST:event_rbtAcqActionPerformed

    private void rbtVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtVenActionPerformed
        this.texTipo.setText("V");
}//GEN-LAST:event_rbtVenActionPerformed

    private void rbtEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEntActionPerformed
        this.texTipo.setText("E");
}//GEN-LAST:event_rbtEntActionPerformed

    private void ivaPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ivaPopupMenuWillBecomeVisible
        JComboBox box = (JComboBox) evt.getSource();
        Object comp = box.getUI().getAccessibleChild(box, 0);
        if (!(comp instanceof JPopupMenu)) {
            return;
        }
        JComponent scrollPane = (JComponent) ((JPopupMenu) comp).getComponent(0);
        Dimension size = new Dimension();
        size.width = box.getPreferredSize().width;
        size.height = scrollPane.getPreferredSize().height;
        scrollPane.setPreferredSize(size);
        //  following line for Tiger
        scrollPane.setMaximumSize(size);
}//GEN-LAST:event_ivaPopupMenuWillBecomeVisible

    private void texSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texSearchKeyPressed

}//GEN-LAST:event_texSearchKeyPressed

    private void texSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texSearchKeyReleased
        SwingUtils.mouse_wait();
        String sql = "select * from articoli where descrizione like " + Db.pc("%" + texSearch.getText() + "%", Types.VARCHAR) + " or codice like " + Db.pc("%" + texSearch.getText() + "%", Types.VARCHAR);
        griglia.dbOpen(Db.getConn(), sql);
        griglia.dbPanel = dati;
        tabCent.setSelectedIndex(1);
        SwingUtils.mouse_def();
}//GEN-LAST:event_texSearchKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SwingUtils.mouse_wait();
        texSearch.setText("");
        String sql = "select * from articoli";
        griglia.dbOpen(Db.getConn(), sql);
        griglia.dbPanel = dati;
        tabCent.setSelectedIndex(1);
        SwingUtils.mouse_def();
}//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDele;
    private javax.swing.JButton butFind;
    private javax.swing.JButton butFirs;
    private javax.swing.JButton butLast;
    private javax.swing.JButton butNew;
    private javax.swing.JButton butNext;
    private javax.swing.JButton butPrev;
    private javax.swing.JButton butSave;
    private javax.swing.JButton butStampaElenco;
    private javax.swing.JButton butUndo;
    private tnxbeans.tnxDbPanel dati;
    private tnxbeans.tnxDbGrid griglia;
    private javax.swing.ButtonGroup grpSel;
    private tnxbeans.tnxComboField iva;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel231;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel labPrez1;
    private javax.swing.JLabel labPrez2;
    private javax.swing.JPanel panAlto;
    private javax.swing.JPanel panDati;
    private javax.swing.JPanel panElen;
    private javax.swing.JRadioButton rbtAcq;
    private javax.swing.JRadioButton rbtEnt;
    private javax.swing.JRadioButton rbtVen;
    private javax.swing.JTabbedPane tabCent;
    private tnxbeans.tnxTextField texCodi;
    private tnxbeans.tnxTextField texDesc;
    private tnxbeans.tnxTextField texPrez;
    private tnxbeans.tnxTextField texPrez1;
    private javax.swing.JTextField texSearch;
    private tnxbeans.tnxTextField texTipo;
    private tnxbeans.tnxTextField texUm;
    private tnxbeans.tnxTextField texUm1;
    // End of variables declaration//GEN-END:variables
}
