/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmImportArtiExcel2.java
 *
 * Created on 11-feb-2010, 11.16.36
 */
package gestioneFatture;

import it.tnx.Db;
import it.tnx.SwingWorker;
import it.tnx.commons.SwingUtils;
import it.tnx.invoicex.InvoicexUtil;
import java.awt.Cursor;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.filechooser.FileFilter;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author mceccarelli
 */
public class frmImportArtiExcel extends javax.swing.JInternalFrame {

    JInternalFrame padre;

    /** Creates new form frmImportArtiExcel */
    public frmImportArtiExcel(JInternalFrame padre) {
        initComponents();
        this.padre = padre;
        comListino.dbOpenList(Db.getConn(), "select descrizione, codice from tipi_listino where ricarico_flag is null or ricarico_flag != 'S'");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comListino = new tnxbeans.tnxComboField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        butNuovoListino = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);
        setTitle("Import articoli da file Excel");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Listino:");

        comListino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("<html>Selezionare un file Excel con le seguenti colonne in ordine:<br>\nA-Codice articolo<br>\nB-Descrizione<br>\nC-Prezzo<br>\nD-Codice IVA<br>\nE-Unità di misura<br>\nF-Codice a barre<br>\nG-Codice Fornitore<br>\nH-Descrizione in inglese<br>\nI-Unità di misura in inglese<br>\n<br>\nSe alcuni campi non sono riempiti non verranno azzerati\n</html>");

        butNuovoListino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/document-new.png"))); // NOI18N
        butNuovoListino.setText("Nuovo Listino");
        butNuovoListino.setPreferredSize(new java.awt.Dimension(180, 25));
        butNuovoListino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNuovoListinoActionPerformed(evt);
            }
        });
        jPanel1.add(butNuovoListino);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/go-jump.png"))); // NOI18N
        jButton2.setText("Scegli il file da importare");
        jButton2.setPreferredSize(new java.awt.Dimension(180, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(comListino, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(comListino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butNuovoListinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNuovoListinoActionPerformed
        frmListini frm = new frmListini(this);
        main.getPadre().openFrame(frm, 600, 400);
}//GEN-LAST:event_butNuovoListinoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        File dirListini = new File(System.getProperty("user.home") + File.separator + ".invoicex" + File.separator + "Listini" + File.separator);
        if (!dirListini.exists()) {
            dirListini.mkdir();
        }

        final JFileChooser fileChoose = new JFileChooser(dirListini);
        FileFilter filter1 = new FileFilter() {

            public boolean accept(File pathname) {
                if (pathname.getAbsolutePath().endsWith(".xls")) {
                    return true;
                } else if (pathname.isDirectory()) {
                    return true;
                } else {
                    return false;
                }
            }

            public String getDescription() {
                return "File XLS (*.xls)";
            }
        };

        fileChoose.addChoosableFileFilter(filter1);
        fileChoose.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int ret = fileChoose.showOpenDialog(this);

        if (ret == javax.swing.JFileChooser.APPROVE_OPTION) {
            try {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                InputStream inp = new FileInputStream(fileChoose.getSelectedFile());

                HSSFWorkbook wb = new HSSFWorkbook(inp);
                final HSSFSheet sheet = wb.getSheetAt(0);
                final int lastRow = sheet.getLastRowNum() + 1;
                final JDialogInsert dialog = new JDialogInsert(main.getPadre(), false, "", lastRow);
                final String listino = String.valueOf(comListino.getSelectedKey());

                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
                try {
                    SwingWorker sw = new SwingWorker() {

                        public Object construct() {
                            try {
                                it.tnx.invoicex.ImportArticoli loader = new it.tnx.invoicex.ImportArticoli(fileChoose.getSelectedFile().getAbsolutePath(), listino, lastRow);
                                loader.insert = dialog;

                                loader.process();
                                dialog.dispose();

                                try {
                                    InvoicexUtil.aggiornaListini();
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                                
                                ((frmArtiConListino) padre).dati.dbRefresh();
                                ((frmArtiConListino) padre).griglia.dbRefresh();
                                ((frmArtiConListino) padre).showListino();
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                            
                            SwingUtils.showInfoMessage(padre, "Importazione completata");
                            return null;
                        }
                    };

                    sw.start();
                } catch (Exception e) {
                    e.printStackTrace();
                }                
            } catch (org.apache.poi.hssf.OldExcelFormatException old) {
                SwingUtils.showErrorMessage(padre, "Il formato del file Excel deve essere 'Excel versions 97/2000/XP/2003'\n" + old.getMessage(), "Formato Excel non supportato");
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton butNuovoListino;
    public tnxbeans.tnxComboField comListino;
    public javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
