/**
 * Invoicex
 * Copyright (c) 2005,2006,2007 Marco Ceccarelli, Tnx snc
 *
 * Questo software è soggetto, e deve essere distribuito con la licenza  
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 * 
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */

package gestioneFatture;

import it.tnx.Db;
import it.tnx.commons.SwingUtils;
import java.io.File;

public class frmListDistRiba
    extends javax.swing.JInternalFrame {

    /** Creates new form frmListCoorBanc */
    public frmListDistRiba() {
        initComponents();

        //azzero la griglia
        griglia.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {
            { null }
        }, new String[] { "" }));

        //setto lengthlarghezze delle colonne
        java.util.Hashtable colsWidthPerc = new java.util.Hashtable();
        colsWidthPerc.put("Numero", new Double(40));
        colsWidthPerc.put("Data di stampa", new Double(40));
        colsWidthPerc.put("Tipo", new Double(20));
        this.griglia.columnsSizePerc = colsWidthPerc;

        //apro la griglia con lengthdistinte
        griglia.flagUsaOrdinamento = true;

        String sql = "SELECT ";
        sql += " d.id AS Numero";
        sql += " , d.data AS 'Data di stampa'";
        sql += " , IF(s.flag_file = 'S', 'File', 'Cartaceo') AS 'Tipo'";
        sql += " FROM distinte_riba d JOIN scadenze s ON s.distinta = d.id";
        sql += " GROUP BY d.id";
        griglia.dbOpen(Db.getConn(), sql);

        try {
            InvoicexEvent event = new InvoicexEvent(this);
            event.type = InvoicexEvent.TYPE_RISTAMPA_DISTINTA_RIBA;
            main.events.fireInvoicexEvent(event);
        } catch (Exception err) {
            err.printStackTrace();
        }
    }

    /** This method is called from within the constructor to

   * initialize the form.

   * WARNING: Do NOT modify this code. The content of this method is

   * always regenerated by the Form Editor.

   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        griglia = new tnxbeans.tnxDbGrid();
        jPanel3 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista distinte Ri.Ba.");

        jPanel2.setMinimumSize(new java.awt.Dimension(254, 46));
        jPanel2.setPreferredSize(new java.awt.Dimension(357, 30));

        jLabel3.setText("fai doppio clic sulla distinta per ristamparla");
        jPanel2.add(jLabel3);

        jPanel1.setLayout(new java.awt.BorderLayout());

        griglia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        griglia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grigliaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(griglia);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .add(10, 10, 10))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grigliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grigliaMouseClicked

        if (evt.getClickCount() == 2) {
            //stampo la distinta
            //lancio anteprima
            try {
//                Runtime.getRuntime().exec("start " + nomeFilePdf);
//                SwingUtils.open(new File(main.wd + "spool/distintaRiba_" + this.griglia.getValueAt(griglia.getSelectedRow(), 0) + ".pdf"));
                System.out.println("Apertura da frmListDistRiba");
                String nomeFile = main.wd + "spool/distintaRiba_" + this.griglia.getValueAt(griglia.getSelectedRow(), 0) + ".pdf";
                Util.start2(nomeFile);
            } catch (Exception err) {
                err.printStackTrace();
            }
        }
    }//GEN-LAST:event_grigliaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public tnxbeans.tnxDbGrid griglia;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
