/**
 * Invoicex
 * Copyright (c) 2005,2006,2007 Marco Ceccarelli, Tnx snc
 *
 * Questo software è soggetto, e deve essere distribuito con la licenza  
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 * 
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */
package gestioneFatture;

import it.tnx.Db;
import java.awt.*;

import javax.swing.*;

public class frmListCoorBanc
        extends javax.swing.JInternalFrame {

    CoordinateBancarie coords;

    /** Creates new form frmListCoorBanc */
    public frmListCoorBanc(CoordinateBancarie coords) {
        this.coords = coords;
        initComponents();

        //azzero la griglia
        griAgen.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{
            {null}}, new String[]{""}));

        //setto lengthlarghezze delle colonne
        java.util.Hashtable colsWidthPerc = new java.util.Hashtable();
        colsWidthPerc.put("abi", new Double(5));
        colsWidthPerc.put("nome", new Double(24));
        colsWidthPerc.put("cab", new Double(6));
        colsWidthPerc.put("cap", new Double(6));
        colsWidthPerc.put("indirizzo", new Double(25));
        colsWidthPerc.put("comune", new Double(15));
        colsWidthPerc.put("provincia", new Double(10));
        colsWidthPerc.put("regione", new Double(10));
        this.griAgen.columnsSizePerc = colsWidthPerc;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        texProvAgen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        texComuAgen = new javax.swing.JTextField();
        comElen = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        texNomeBanc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        griAgen = new tnxbeans.tnxDbGrid();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Coordinate bancarie");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.setPreferredSize(new java.awt.Dimension(357, 100));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Provincia agenzia");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 115, 20));
        texProvAgen.setColumns(15);
        texProvAgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texProvAgenActionPerformed(evt);
            }
        });
        jPanel2.add(texProvAgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Comune agenzia");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 20));
        texComuAgen.setColumns(15);
        texComuAgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texComuAgenActionPerformed(evt);
            }
        });
        jPanel2.add(texComuAgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));
        comElen.setText("Elenca");
        comElen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comElenActionPerformed(evt);
            }
        });
        jPanel2.add(comElen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 20));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 11));
        jLabel4.setText("Inserire almeno uno o pi\u00f9 campi e premere 'Elenca' per vedere i risultati della ricerca.");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nome banca");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 115, 20));
        texNomeBanc.setColumns(15);
        texNomeBanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texNomeBancActionPerformed(evt);
            }
        });
        jPanel2.add(texNomeBanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 11));
        jLabel6.setText("(scritta per inter. Es.: 'FIRENZE')");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));
        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);
        jPanel1.setLayout(new java.awt.BorderLayout());
        griAgen.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {
            { null, null, null, null }, { null, null, null, null }, 
            { null, null, null, null }, { null, null, null, null }
        }, new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
        griAgen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                griAgenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(griAgen);
        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jLabel3.setText("fai doppio clic sulla filiale per selezionarla");
        jPanel3.add(jLabel3);
        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-END:initComponents

    private void texNomeBancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texNomeBancActionPerformed
        comElenActionPerformed(null);
    }//GEN-LAST:event_texNomeBancActionPerformed

    private void griAgenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_griAgenMouseClicked

        if (evt.getClickCount() == 2) {

            //ritorno le info tramite coords
            this.coords.setAbi(this.griAgen.getValueAt(griAgen.getSelectedRow(), 0).toString());
            this.coords.setCab(this.griAgen.getValueAt(griAgen.getSelectedRow(), 2).toString());
            
            String descAbi = "";
            String descCab = "";
            descAbi = Db.nz(this.griAgen.getValueAt(griAgen.getSelectedRow(), 1).toString(), "");
            descCab = Db.nz(this.griAgen.getValueAt(griAgen.getSelectedRow(), 3).toString(), "");
            descCab += " " + Db.nz(this.griAgen.getValueAt(griAgen.getSelectedRow(), 4).toString(), "");
            descCab += ", " + Db.nz(this.griAgen.getValueAt(griAgen.getSelectedRow(), 5).toString(), "");
            descCab += " (" + Db.nz(this.griAgen.getValueAt(griAgen.getSelectedRow(), 6).toString(), "") + ")";
            this.coords.setDescrizioneAbi(descAbi);
            this.coords.setDescrizioneCab(descCab);
            
            this.dispose();
        }
    }//GEN-LAST:event_griAgenMouseClicked

    private void texComuAgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texComuAgenActionPerformed
        comElenActionPerformed(null);
    }//GEN-LAST:event_texComuAgenActionPerformed

    private void texProvAgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texProvAgenActionPerformed
        comElenActionPerformed(null);
    }//GEN-LAST:event_texProvAgenActionPerformed

    private void comElenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comElenActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));

        String sql = "select banche_abi.abi,";
        sql += " banche_abi.nome,";
        sql += " banche_cab.cab,";
        sql += " banche_cab.cap,";
        sql += " banche_cab.indirizzo,";
        sql += " comuni.comune,";
        sql += " comuni.provincia,";
        sql += " comuni.regione";
        sql += " from (banche_abi left join banche_cab on banche_abi.abi = banche_cab.abi)";
        sql += " left join comuni on banche_cab.codice_comune = comuni.codice";
        sql += " where banche_abi.nome LIKE " + Db.pc("%" + this.texNomeBanc.getText() + "%", "VARCHAR");
        sql += " and comuni.provincia LIKE " + Db.pc(this.texProvAgen.getText() + "%", "VARCHAR");
        sql += " and comuni.comune LIKE " + Db.pc(this.texComuAgen.getText() + "%", "VARCHAR");
        sql += " order by banche_abi.nome, comuni.comune, banche_cab.indirizzo";
        sql += " LIMIT 1000";

        //SAMUELE INNOCENTI
        //filtro altrimenti si attende troppo 
        if ((this.texNomeBanc.getText().length() == 0) & (this.texProvAgen.getText().length() == 0) & (this.texComuAgen.getText().length() == 0)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Inserisci almeno un dato nelle caselle di ricerca");
        } else {
            this.griAgen.dbOpen(Db.getConn(), sql);
        }
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        
    }//GEN-LAST:event_comElenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField texNomeBanc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton comElen;
    private javax.swing.JTextField texProvAgen;
    private tnxbeans.tnxDbGrid griAgen;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField texComuAgen;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel1;

    // End of variables declaration//GEN-END:variables
}
