/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmSegnalaRapporti.java
 *
 * Created on 3-dic-2009, 11.12.55
 */

package gestioneFatture;

import it.tnx.Db;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Toce Alessio
 */
public class frmSegnalaRapporti extends javax.swing.JInternalFrame {

    /** Creates new form frmSegnalaRapporti */
    public frmSegnalaRapporti() {
        initComponents();

        dati_griglia.dbOpen(Db.getConn(), "select c.ragione_sociale, r.* from clie_forn_rapporti r join clie_forn c on r.cliente = c.codice");
        griglia.flagUsaThread = false;
        java.util.Hashtable colsWidthPercRapporti = new java.util.Hashtable();
        colsWidthPercRapporti.put("Rag. Sociale", new Double(20));
        colsWidthPercRapporti.put("id", new Double(0));
        colsWidthPercRapporti.put("cliente", new Double(0));
        colsWidthPercRapporti.put("data", new Double(20));
        colsWidthPercRapporti.put("data_avviso", new Double(0));
        colsWidthPercRapporti.put("testo", new Double(60));
        colsWidthPercRapporti.put("segnalato", new Double(0));
        griglia.columnsSizePerc = colsWidthPercRapporti;

        griglia.dbOpen(Db.getConn(), "select c.ragione_sociale as 'Rag. Sociale', r.* from clie_forn_rapporti r join clie_forn c on r.cliente = c.codice where data_avviso <= CURDATE() and segnalato = 'N'");

        String id = String.valueOf(griglia.getValueAt(griglia.getSelectedRow(), griglia.getColumnByName("id")));

        
        dati.dbNomeTabella = "clie_forn_rapporti";
        Vector chiavi = new Vector();
        chiavi.add("id");
        dati.dbChiave = chiavi;

        dati.butSave = butSalva;
        dati.messaggio_nuovo_manuale = true;
        dati.dbOpen(Db.getConn(), "select c.ragione_sociale, r.* from clie_forn_rapporti r join clie_forn c on r.cliente = c.codice where r.id = " + id);

        griglia.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                String id = String.valueOf(griglia.getValueAt(griglia.getSelectedRow(), griglia.getColumnByName("id")));
                dati.dbOpen(Db.getConn(), "select c.ragione_sociale, r.* from clie_forn_rapporti r join clie_forn c on r.cliente = c.codice where r.id = " + id);
                dati.dbRefresh();
            }
        });

        this.texId.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dati_griglia = new tnxbeans.tnxDbPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        griglia = new tnxbeans.tnxDbGrid();
        jLabel1 = new javax.swing.JLabel();
        dati = new tnxbeans.tnxDbPanel();
        jLabel2 = new javax.swing.JLabel();
        tnxTextField1 = new tnxbeans.tnxTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tnxTextField2 = new tnxbeans.tnxTextField();
        jLabel5 = new javax.swing.JLabel();
        tnxMemoField1 = new tnxbeans.tnxMemoField();
        cheSmetti = new tnxbeans.tnxCheckBox();
        butSalva = new javax.swing.JButton();
        texId = new tnxbeans.tnxTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Avvisi da segnalare");

        griglia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(griglia);

        jLabel1.setText("Avvisi");

        org.jdesktop.layout.GroupLayout dati_grigliaLayout = new org.jdesktop.layout.GroupLayout(dati_griglia);
        dati_griglia.setLayout(dati_grigliaLayout);
        dati_grigliaLayout.setHorizontalGroup(
            dati_grigliaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dati_grigliaLayout.createSequentialGroup()
                .addContainerGap()
                .add(dati_grigliaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(jLabel1))
                .add(18, 18, 18))
        );
        dati_grigliaLayout.setVerticalGroup(
            dati_grigliaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dati_grigliaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Dettaglio Avviso");

        tnxTextField1.setEditable(false);
        tnxTextField1.setDbNomeCampo("cliente");

        jLabel3.setText("Cliente:");

        jLabel4.setText("Data:");

        tnxTextField2.setEditable(false);
        tnxTextField2.setDbNomeCampo("data");
        tnxTextField2.setDbTipoCampo("data");

        jLabel5.setText("Testo:");

        tnxMemoField1.setDbNomeCampo("testo");

        cheSmetti.setText("Non segnalare più questo avviso");
        cheSmetti.setDbNomeCampo("segnalato");
        cheSmetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheSmettiActionPerformed(evt);
            }
        });

        butSalva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/devices/media-floppy.png"))); // NOI18N
        butSalva.setText("Salva");
        butSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSalvaActionPerformed(evt);
            }
        });

        texId.setBackground(new java.awt.Color(255, 153, 153));
        texId.setText("tnxTextField3");
        texId.setDbNomeCampo("id");

        org.jdesktop.layout.GroupLayout datiLayout = new org.jdesktop.layout.GroupLayout(dati);
        dati.setLayout(datiLayout);
        datiLayout.setHorizontalGroup(
            datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(datiLayout.createSequentialGroup()
                .addContainerGap()
                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, datiLayout.createSequentialGroup()
                        .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, datiLayout.createSequentialGroup()
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(texId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(datiLayout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(tnxTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(tnxTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 235, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, datiLayout.createSequentialGroup()
                                .add(cheSmetti, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(butSalva))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, tnxMemoField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(23, 23, 23)))
                .add(0, 0, 0))
        );
        datiLayout.setVerticalGroup(
            datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(datiLayout.createSequentialGroup()
                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(texId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(tnxTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tnxTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tnxMemoField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(datiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cheSmetti, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(butSalva))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dati_griglia, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(dati, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(dati_griglia, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dati, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cheSmettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheSmettiActionPerformed
//        if(cheSmetti.isSelected()){
//            int res = JOptionPane.showConfirmDialog(this, "Con questa opzione non potrai più vedere il seguente avviso. Continuare?", "Conferma", JOptionPane.YES_NO_CANCEL_OPTION);
//
//            if(res != JOptionPane.YES_OPTION){
//                cheSmetti.setSelected(false);
//            }
//        }
    }//GEN-LAST:event_cheSmettiActionPerformed

    private void butSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalvaActionPerformed
        dati.dbSave();
        this.griglia.dbRefresh();

        dati_griglia.dbRefresh();

        if(griglia.getRowCount() == 0){
            this.setVisible(false);
            this.dispose();
        } else {
            String id = String.valueOf(griglia.getValueAt(griglia.getSelectedRow(), griglia.getColumnByName("id")));
            dati.dbOpen(Db.getConn(), "select c.ragione_sociale, r.* from clie_forn_rapporti r join clie_forn c on r.cliente = c.codice where r.id = " + id);
        }
    }//GEN-LAST:event_butSalvaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSegnalaRapporti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butSalva;
    private tnxbeans.tnxCheckBox cheSmetti;
    private tnxbeans.tnxDbPanel dati;
    private tnxbeans.tnxDbPanel dati_griglia;
    private tnxbeans.tnxDbGrid griglia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private tnxbeans.tnxTextField texId;
    private tnxbeans.tnxMemoField tnxMemoField1;
    private tnxbeans.tnxTextField tnxTextField1;
    private tnxbeans.tnxTextField tnxTextField2;
    // End of variables declaration//GEN-END:variables

}
