/**
 * Invoicex
 * Copyright (c) 2005,2006,2007 Marco Ceccarelli, Tnx snc
 *
 * Questo software è soggetto, e deve essere distribuito con la licenza  
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 * 
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */



/*

 * frmZoomDesc.java

 *

 * Created on January 27, 2005, 12:28 PM

 */
package gestioneFatture;


/**

 *

 * @author  marco

 */
public class frmZoomDesc
    extends javax.swing.JInternalFrame {

    javax.swing.JTable griglia;
    public FoglioSelectionListener selectList;

    /** Creates new form frmZoomDesc */
    public frmZoomDesc() {
        initComponents();
    }

    public void setGriglia(javax.swing.JTable table) {
        this.griglia = table;
    }

    public void setDesc(String text) {
        this.texDescrizione.setText(text);
    }

    public String getDesc() {

        return texDescrizione.getText();
    }

    /** This method is called from within the constructor to

     * initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is

     * always regenerated by the Form Editor.

     */
    private void initComponents() { //GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        texDescrizione = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        comSalva = new javax.swing.JButton();
        setTitle("Zoom");
        texDescrizione.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                texDescrizioneFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(texDescrizione);
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        comSalva.setText("salva");
        comSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comSalvaActionPerformed(evt);
            }
        });
        jPanel1.add(comSalva);
        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);
        pack();
    } //GEN-END:initComponents

    private void comSalvaActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_comSalvaActionPerformed
        griglia.setValueAt(getDesc(), griglia.getSelectedRow(), 2);
    } //GEN-LAST:event_comSalvaActionPerformed

    private void texDescrizioneFocusGained(java.awt.event.FocusEvent evt) { //GEN-FIRST:event_texDescrizioneFocusGained
        selectList.setFlagSalvare(true);
    } //GEN-LAST:event_texDescrizioneFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comSalva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texDescrizione;

    // End of variables declaration//GEN-END:variables
}