/**
 * Invoicex
 * Copyright (c) 2005,2006,2007 Marco Ceccarelli, Tnx snc
 *
 * Questo software è soggetto, e deve essere distribuito con la licenza  
 * GNU General Public License, Version 2. La licenza accompagna il software
 * o potete trovarne una copia alla Free Software Foundation http://www.fsf.org .
 *
 * This software is subject to, and may be distributed under, the
 * GNU General Public License, Version 2. The license should have
 * accompanied the software or you may obtain a copy of the license
 * from the Free Software Foundation at http://www.fsf.org .
 * 
 * --
 * Marco Ceccarelli (m.ceccarelli@tnx.it)
 * Tnx snc (http://www.tnx.it)
 *
 */



package gestioneFatture;

import javax.swing.JOptionPane;

public class JDialogInstInfo
    extends javax.swing.JDialog {

    /** Creates new form JDialogInstInfo */
    public JDialogInstInfo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //        try {
        //            Statement stat = Db.conn.createStatement();
        //            ResultSet r = stat.executeQuery("select alpha2, name from iso3166 order by name");
        //            while (r.next()) {
        //                Nazione n = new Nazione();
        //                n.alpha2 = r.getString("alpha2");
        //                n.nome = r.getString("name");
        //                comNazioni.addItem(n);
        //            }
        //        } catch (Exception err) {
        //            err.printStackTrace();
        //        }
    }

    class Nazione {

        public String alpha2;
        public String nome;

        public String toString() {

            return nome;
        }
    }

    private boolean isEmail(String email) {

        if (email.length() < 4)

            return false;

        if (email.indexOf('@') < 0)

            return false;

        int i = email.indexOf('@');

        if (email.substring(i).indexOf('.') < 0)

            return false;

        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        texEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        texNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        texCognome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        texSeriale = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informazioni installazione");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/22x22/devices/media-floppy.png"))); // NOI18N
        jButton1.setText("Conferma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 205, 120, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/22x22/actions/edit-undo.png"))); // NOI18N
        jButton2.setText("Annulla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 205, 120, -1));

        jLabel1.setText("<html>Questa \u00e8 la prima volta che stai utilizzando questo programma.<br>Per iniziare ti chiediamo di indicarci il tuo indirizzo di email.<br>Il programma invier\u00e0 i dati al nostro server esclusivamente<br>per alimentare le statistiche di utilizzo.</html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        texEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texEmailActionPerformed(evt);
            }
        });
        getContentPane().add(texEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 75, 195, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 65, 20));

        jLabel5.setText("(obbligatorio)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nome");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 65, 20));

        texNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texNomeActionPerformed(evt);
            }
        });
        getContentPane().add(texNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 265, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Cognome");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 65, 20));

        texCognome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texCognomeActionPerformed(evt);
            }
        });
        getContentPane().add(texCognome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 155, 265, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Id");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 65, 20));

        texSeriale.setEnabled(false);
        texSeriale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texSerialeActionPerformed(evt);
            }
        });
        getContentPane().add(texSeriale, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 195, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texSerialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texSerialeActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_texSerialeActionPerformed

    private void texCognomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texCognomeActionPerformed
        jButton1ActionPerformed(null);
    }//GEN-LAST:event_texCognomeActionPerformed

    private void texNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texNomeActionPerformed
        jButton1ActionPerformed(null);
    }//GEN-LAST:event_texNomeActionPerformed

    private void texEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texEmailActionPerformed
        jButton1ActionPerformed(null);
    }//GEN-LAST:event_texEmailActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        int ret = JOptionPane.showConfirmDialog(this, "Sicuro di annullare l'invio dei dati ?", "Attenzione", JOptionPane.YES_NO_OPTION);

        if (ret == JOptionPane.YES_OPTION) {
            this.dispose();
            gestioneFatture.main.exitMain();
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int ret = JOptionPane.showConfirmDialog(this, "Sicuro di annullare l'invio dei dati ?", "Attenzione", JOptionPane.YES_NO_OPTION);

        if (ret == JOptionPane.YES_OPTION) {
            this.dispose();
            gestioneFatture.main.exitMain();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //controllare email
        String email = texEmail.getText();

        if (!isEmail(email)) {
            JOptionPane.showMessageDialog(this, "L'indirizzo di email non è valido !", "Attenzione", JOptionPane.INFORMATION_MESSAGE);
        } else {
            gestioneFatture.main.inst_email = email;
            gestioneFatture.main.inst_nome = texNome.getText();
            gestioneFatture.main.inst_cognome = texCognome.getText();

            //            gestioneFatture.main.inst_nazione = ((Nazione)comNazioni.getSelectedItem()).alpha2;
            setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDialogInstInfo(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField texCognome;
    public javax.swing.JTextField texEmail;
    public javax.swing.JTextField texNome;
    public javax.swing.JTextField texSeriale;
    // End of variables declaration//GEN-END:variables
}