/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogChooseListino.java
 *
 * Created on 4-feb-2010, 9.48.01
 */
package gestioneFatture;

import com.jhlabs.image.GlowFilter;
import it.tnx.accessoUtenti.Utente;
import it.tnx.commons.DbUtils;
import it.tnx.commons.SwingUtils;
import it.tnx.invoicex.InvoicexUtil;
import java.awt.Frame;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.sql.Types;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.ToolTipManager;

/**
 *
 * @author Toce Alessio
 */
public class JDialogAccesso extends JDialog {

    private boolean canLogin;
    private boolean annullaLogin;
    BufferedImage img0;
    BufferedImage img1;

    /** Creates new form JDialogChooseListino */
    public JDialogAccesso(Frame parent, boolean modal, int tentativi) {
        super(parent, modal);
        initComponents();

        if (main.fileIni.getValueBoolean("accesso", "ricora_login", true)) {
            cheRicordaUtente.setSelected(true);
            texUsername.setText(main.fileIni.getValue("accesso", "login_utente", ""));
            if (main.fileIni.getValue("accesso", "login_utente", "").length() > 0) {
                texPassword.requestFocus();
            } else {
                texUsername.requestFocus();
            }
        } else {
            cheRicordaUtente.setSelected(false);
            texUsername.requestFocus();
        }

        canLogin = false;
        annullaLogin = false;
        if (tentativi > 0) {
            int restanti = 3 - tentativi;

            if (restanti > 1) {
                this.setTitle("Errore nel login, altri " + restanti + " tentativi rimanenti");
            } else {
                this.setTitle("Errore nel login, 1 tentativo rimanente");
            }
        }

        //icona help
        //BufferedImage img = createTextImage(getText(), getFont());
        Icon icon = jLabel3.getIcon();
        int imgW = icon.getIconWidth();
        int imgH = icon.getIconHeight();
        img1 = new BufferedImage(imgW, imgH, BufferedImage.TYPE_INT_ARGB);
        img0 = new BufferedImage(imgW, imgH, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = (Graphics2D) img1.getGraphics();
        Graphics2D g2d0 = (Graphics2D) img0.getGraphics();
        icon.paintIcon(null, g2d, 0, 0);
        icon.paintIcon(null, g2d0, 0, 0);
        g2d.dispose();
        g2d0.dispose();
        GlowFilter gf = new GlowFilter();
        gf.setAmount(0.15f);
        gf.filter(img1, img1);
        jLabel3.addMouseListener(new MouseListener() {

            public void mouseClicked(MouseEvent e) {
            }

            public void mousePressed(MouseEvent e) {
            }

            public void mouseReleased(MouseEvent e) {
            }

            public void mouseEntered(MouseEvent e) {
                System.out.println("entered");
                jLabel3.setIcon(new ImageIcon(img1));
            }

            public void mouseExited(MouseEvent e) {
                System.out.println("exited");
                jLabel3.setIcon(new ImageIcon(img0));
            }
        });
        ToolTipManager ttm = ToolTipManager.sharedInstance();
        ttm.setDismissDelay(10000);
        ttm.setInitialDelay(200);
    }

    public boolean canLogin() {
        return canLogin;
    }

    public boolean annullaLogin() {
        return annullaLogin;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        butLogin = new javax.swing.JButton();
        butAnnulla = new javax.swing.JButton();
        texPassword = new javax.swing.JPasswordField();
        texUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cheRicordaUtente = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setTitle("Invoicex Login");
        setBackground(new java.awt.Color(224, 223, 227));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        butLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/edit-redo.png"))); // NOI18N
        butLogin.setText("Login");
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });

        butAnnulla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/16x16/actions/edit-undo.png"))); // NOI18N
        butAnnulla.setText("Annulla");
        butAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnullaActionPerformed(evt);
            }
        });

        texPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                texPasswordKeyReleased(evt);
            }
        });

        texUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                texUsernameFocusGained(evt);
            }
        });
        texUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                texUsernameKeyReleased(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Utente");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password");

        cheRicordaUtente.setText("Ricorda utente al prossimo avvio");
        cheRicordaUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheRicordaUtenteActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/22x22/apps/help-browser.png"))); // NOI18N
        jLabel3.setToolTipText("Se è la prima volta che hai attivato la gestione utenti, Utente e Password sono admin/admin");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .add(4, 4, 4)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(texPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .add(texUsername, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .add(cheRicordaUtente)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 83, Short.MAX_VALUE)
                        .add(butAnnulla, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(butLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {jLabel1, jLabel2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(texUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(texPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cheRicordaUtente)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(butLogin)
                        .add(butAnnulla))
                    .add(jLabel3))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {jLabel1, texUsername}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {jLabel2, texPassword}, org.jdesktop.layout.GroupLayout.VERTICAL);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void butAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnullaActionPerformed
        canLogin = false;
        annullaLogin = true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_butAnnullaActionPerformed

    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed
        try {
            String username = this.texUsername.getText();
            String password = new String(this.texPassword.getPassword());

            if (username.equals("")) {
                canLogin = false;
                SwingUtils.showErrorMessage(this, "Inserisci username e password per accedere", "Errore di connessione", true);
            } else if (username.equalsIgnoreCase("tnx") && InvoicexUtil.md5(password).equals("acfd17732e8ed65411cd34a46b1f7884")) {
                canLogin = true;
                main.utente = new Utente(1);
            } else {
                // Creo password in MD5
                String md5Password = InvoicexUtil.md5(password);

                String query = "SELECT id FROM accessi_utenti WHERE username = " + Db.pc(username, Types.VARCHAR) + " AND password = " + Db.pc(md5Password, Types.VARCHAR);
                System.out.println("query = " + query);
                String idUtente = Db.nz(String.valueOf(DbUtils.getObject(Db.getConn(), query)), "-1");

                canLogin = true;
                main.utente = new Utente(Integer.parseInt(idUtente));

                main.fileIni.setValue("accesso", "ricora_login", this.cheRicordaUtente.isSelected());
                if (cheRicordaUtente.isSelected()) {
                    main.fileIni.setValue("accesso", "login_utente", main.utente.getNomeUtente());
                } else {
                    main.fileIni.setValue("accesso", "login_utente", "");
                }

                System.out.println("prima insert");
                Db.executeSql("INSERT INTO accessi_log SET utente = " + Db.pc(main.utente.getNomeUtente(), Types.VARCHAR));
                System.out.println("dopo insert");
            }
        } catch (Throwable t) {
            t.printStackTrace();
            canLogin = false;
            SwingUtils.showErrorMessage(this, "Username o password errati", "Errore di connessione", true);
        }
        System.out.println("set visible false");
        setVisible(false);
    }//GEN-LAST:event_butLoginActionPerformed

    private void texPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texPasswordKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            butLoginActionPerformed(null);
        }
    }//GEN-LAST:event_texPasswordKeyReleased

    private void texUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texUsernameFocusGained
        this.texUsername.setSelectionStart(0);
        this.texUsername.setSelectionEnd(this.texUsername.getText().length());
    }//GEN-LAST:event_texUsernameFocusGained

    private void texUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texUsernameKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            butLoginActionPerformed(null);
        }
    }//GEN-LAST:event_texUsernameKeyReleased

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
    }//GEN-LAST:event_jLabel3MouseEntered

    private void cheRicordaUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheRicordaUtenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheRicordaUtenteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAnnulla;
    private javax.swing.JButton butLogin;
    private javax.swing.JCheckBox cheRicordaUtente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPasswordField texPassword;
    private javax.swing.JTextField texUsername;
    // End of variables declaration//GEN-END:variables
}
