/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuPanelNews.java
 *
 * Created on 12-lug-2011, 17.18.51
 */
package gestioneFatture;

import it.tnx.commons.SwingUtils;
import javax.swing.JInternalFrame;
import javax.swing.event.HyperlinkEvent;

/**
 *
 * @author mceccarelli
 */
public class MenuPanelNews extends javax.swing.JPanel {

    public String id = "";
    public JInternalFrame padre = null;
    public Thread thread_auto_chiusura = null;

    /** Creates new form MenuPanelNews */
    public MenuPanelNews() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data = new javax.swing.JLabel();
        titolo = new javax.swing.JLabel();
        chiudi = new javax.swing.JButton();
        link = new org.jdesktop.swingx.JXHyperlink();
        jSeparator1 = new javax.swing.JSeparator();
        autochiusura = new javax.swing.JLabel();
        non = new javax.swing.JCheckBox();
        corpo = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        icona = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 100));

        data.setForeground(new java.awt.Color(51, 51, 51));
        data.setText("data");
        data.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        titolo.setFont(titolo.getFont().deriveFont(titolo.getFont().getStyle() | java.awt.Font.BOLD, titolo.getFont().getSize()+3));
        titolo.setText("titolo");
        titolo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        chiudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/22x22/emblems/emblem-unreadable.png"))); // NOI18N
        chiudi.setToolTipText("Chiudi la news");
        chiudi.setBorder(null);
        chiudi.setBorderPainted(false);
        chiudi.setContentAreaFilled(false);
        chiudi.setFocusPainted(false);
        chiudi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/22x22/emblems/emblem-unreadable-pressed.png"))); // NOI18N
        chiudi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/22x22/emblems/emblem-unreadable-over.png"))); // NOI18N

        link.setText("link");
        link.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        autochiusura.setFont(autochiusura.getFont().deriveFont(autochiusura.getFont().getSize()-1f));
        autochiusura.setForeground(javax.swing.UIManager.getDefaults().getColor("TextField.inactiveForeground"));

        non.setFont(non.getFont().deriveFont(non.getFont().getSize()-1f));
        non.setForeground(new java.awt.Color(51, 51, 51));
        non.setText("non visualizzare più");
        non.setToolTipText("Se non spunti questa casella la news verrà visualizzata fino a tre volte");
        non.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        corpo.setBorder(null);
        corpo.setContentType("text/html");
        corpo.setEditable(false);
        corpo.setOpaque(false);
        corpo.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                corpoHyperlinkUpdate(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/tango-icon-theme-080/22x22/status/weather-clear.png"))); // NOI18N
        jPanel1.add(icona, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, link, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, corpo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(data)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 383, Short.MAX_VALUE)
                        .add(autochiusura)
                        .add(6, 6, 6)
                        .add(non)
                        .add(6, 6, 6)
                        .add(chiudi))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, titolo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(non)
                                .add(autochiusura))
                            .add(chiudi)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(1, 1, 1))
                    .add(layout.createSequentialGroup()
                        .add(data, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(titolo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(corpo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(link, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void corpoHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_corpoHyperlinkUpdate
        if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            final HyperlinkEvent fevt = evt;
            Thread t = new Thread("link news") {

                public void run() {
                    try {
                        SwingUtils.openUrl(fevt.getURL());
                    } catch (Exception e) {
                    }
                }
            };
            t.start();
        }
    }//GEN-LAST:event_corpoHyperlinkUpdate
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel autochiusura;
    public javax.swing.JButton chiudi;
    public javax.swing.JTextPane corpo;
    public javax.swing.JLabel data;
    public javax.swing.JLabel icona;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public org.jdesktop.swingx.JXHyperlink link;
    public javax.swing.JCheckBox non;
    public javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
