/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 * Created on 28-giu-2010, 10.53.38
 */
package gestioneFatture;

import it.tnx.Db;
import it.tnx.invoicex.data.DatiAzienda;
import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author mceccarelli
 */
public class MenuFrame extends javax.swing.JFrame {

    public MenuPanel menuPanel = null;
    public org.jdesktop.swingx.JXBusyLabel lblInfoLoading2;
    public JLabel labmess2;

    /** Creates new form Menu */
    public MenuFrame() {
        menuPanel = new MenuPanel();
        getContentPane().add(menuPanel, java.awt.BorderLayout.CENTER);
        setJMenuBar(menuPanel.menBar);
        initComponents();
        lblInfoLoading2 = getMenuPanel().lblInfoLoading2;
        labmess2 = getMenuPanel().labmess2;

    }

    public MenuPanel getMenuPanel() {
        return (MenuPanel) menuPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("formWindowClosing");
        getMenuPanel().exitForm(evt);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String lef = UIManager.getLookAndFeel().getName();
        Color backColor = getMenuPanel().desktop.getBackground();
        if (lef.startsWith("Substance")) {
            backColor = UIManager.getColor("Label.background");
        }
        int somma = (backColor.getBlue() + backColor.getGreen() + backColor.getRed()) / 3;
        if (somma > 130) {
            lblInfoLoading2.setForeground(Color.black);
            labmess2.setForeground(Color.black);
        } else {
            lblInfoLoading2.setForeground(Color.white);
            labmess2.setForeground(Color.white);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public void aggiornaTitle() {
        setTitle("Invoicex " + (main.versione == null ? "" : main.versione) + " - ver. " + main.version.toString() + " (" + MenuPanel.getBuildH(main.build) + ")" + " - Database: " + Db.dbNameDB);
        if (main.attivazione.getIdRegistrazione() != null && main.attivazione.getIdRegistrazione() > 0) {
            setTitle(getTitle() + " - id " + main.attivazione.getIdRegistrazione());
        }
        if (main.utente != null) {
            setTitle(getTitle() + " - utente: " + main.utente.getNomeUtente());
        }
        try {
            DatiAzienda dati = main.attivazione.getDatiAzienda();
            if (dati != null) {
                if (dati.getRagione_sociale() != null) {
                    setTitle(getTitle() + " - " + StringUtils.abbreviate(dati.getRagione_sociale(), 50));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void closeFrame(JInternalFrame frame) {
        //metodo fittizio per retrocompatibilità
    }
}
