/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tnxMemoFieldLangPanel.java
 *
 * Created on 24-dic-2010, 9.52.25
 */
package tnxbeans;

import java.awt.AlphaComposite;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Composite;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JViewport;
import javax.swing.ScrollPaneConstants;
import javax.swing.border.LineBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author mceccarelli
 */
public class tnxMemoFieldLang extends javax.swing.JPanel implements BasicField {

    private List<String> lang = null;
    private List<JScrollPane> scroll;
    private List<JTextArea> textarea;
    private Map<String, JTextArea> lang_area = null;
    private List<JButton> buttons;
    public String dbNomeCampo;
    public String dbTipoCampo;
    public boolean dbRiempire = true;
    public boolean dbSalvare = true;
    public boolean dbModificato = false;
    int margin = 1;

    /** Creates new form tnxMemoFieldLangPanel */
    public tnxMemoFieldLang() {
        initComponents();
        setLayout(new LayoutManager() {

            public void addLayoutComponent(String name, Component comp) {
            }

            public void removeLayoutComponent(Component comp) {
            }

            public Dimension preferredLayoutSize(Container parent) {
                return new Dimension(50, 20);
            }

            public Dimension minimumLayoutSize(Container parent) {
                return new Dimension(50, 20);
            }

            public void layoutContainer(Container parent) {
                layoutComps();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the lang
     */
    public List<String> getLang() {
        return lang;
    }

    /**
     * @param lang the lang to set
     */
    public void setLang(List<String> lang) {
        this.lang = lang;

        removeAll();

        setTextarea(new ArrayList<JTextArea>());
        setScroll(new ArrayList<JScrollPane>());
        setLang_area((Map<String, JTextArea>) new HashMap());
        for (String l : lang) {
            JScrollPane s = new JScrollPane();
            s.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            s.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
            LangJTextArea a = new LangJTextArea();
            a.addFocusListener(new FocusListener() {
                public void focusGained(FocusEvent e) {
                    for (FocusListener f : tnxMemoFieldLang.this.getFocusListeners()) {
                        f.focusGained(e);
                    }
                }

                public void focusLost(FocusEvent e) {
                    for (FocusListener f : tnxMemoFieldLang.this.getFocusListeners()) {
                        f.focusLost(e);
                    }
                }
            });
            a.getDocument().addDocumentListener(new DocumentListener() {
                public void insertUpdate(DocumentEvent e) {
                    change();
                }
                public void removeUpdate(DocumentEvent e) {
                    change();
                }
                public void changedUpdate(DocumentEvent e) {
                    change();
                }
                public void change() {
                    tnxMemoFieldLang.this.dbModificato = true;
                    if (tnxMemoFieldLang.this.getParent() instanceof tnxDbPanel) {
                        tnxDbPanel temp = (tnxDbPanel)tnxMemoFieldLang.this.getParent();
                        if (temp.getParentPanel() != null) temp = temp.getParentPanel();
                        boolean res = temp.dbCheckModificati();
                    }
                }
            });
            a.lang = l;
            s.setViewportView(a);
            getScroll().add(s);
            getTextarea().add(a);
            add(s);
            getLang_area().put(l, a);
        }

        layoutComps();
    }

    private void layoutComps() {
        if (getLang() != null) {
            int langs = getLang().size();
            int w = getWidth();
            int h = getHeight();
            int ws = (w / langs);
            int i = 0;
            for (String l : getLang()) {
                JScrollPane s = getScroll().get(i);
                if (i == getLang().size() - 1) {
                    s.setBounds((ws * i) + margin, margin, ws - (margin * 2), h - (margin * 2));
                } else {
                    s.setBounds((ws * i) + margin, margin, ws - (margin), h - (margin * 2));
                }
                i++;
            }
        }
    }

    /**
     * @return the lang_area
     */
    public Map<String, JTextArea> getLang_area() {
        return lang_area;
    }

    /**
     * @param lang_area the lang_area to set
     */
    public void setLang_area(Map<String, JTextArea> lang_area) {
        this.lang_area = lang_area;
    }

    public static class LangJTextArea extends JTextArea {

        public String lang = null;
        Locale locsel = null;
        String locsel_country = null;

        public LangJTextArea() {
            setOpaque(false);
        }

        @Override
        protected void paintComponent(Graphics g) {

            Graphics2D g2 = (Graphics2D) g;
            Color old_color = g2.getColor();
            Font old_font = g2.getFont();
            Composite old_comp = g2.getComposite();

            g2.setColor(getBackground());
            g2.fillRect(0, 0, getWidth(), getHeight());

            int xrif = (int) (((JViewport) getParent()).getViewRect().getWidth() + ((JViewport) getParent()).getViewRect().getX());
            int yrif = (int) (((JViewport) getParent()).getViewRect().getHeight() + ((JViewport) getParent()).getViewRect().getY());

            if (locsel == null) {
                String lang2 = lang;
                if (lang2.equalsIgnoreCase("en")) {
                    locsel_country = "Great Britain";
                } else {
                    locsel = new Locale(lang.toLowerCase(), lang2.toUpperCase());
                    System.out.println(locsel);
                    locsel_country = locsel.getDisplayCountry(Locale.ENGLISH);
                    System.out.println(locsel_country);
                }
            }

            g2.setColor(new Color(old_color.getRed(), old_color.getGreen(), old_color.getBlue(), 50));
            g2.setFont(old_font.deriveFont(10f));
            g2.drawString(lang.toUpperCase(), xrif - 45, yrif - 10);
            try {
                ImageIcon flag = new ImageIcon(getClass().getResource("/flags/24/" + locsel_country + ".png"));
                g2.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.2f));
                g2.drawImage(flag.getImage(), xrif - 30, yrif - 26, null);
            } catch (Exception e) {
            }

            g2.setColor(old_color);
            g2.setFont(old_font);
            g2.setComposite(old_comp);

            super.paintComponent(g2);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        JFrame f = new JFrame("test");
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setLayout(new BorderLayout(2, 2));
        tnxMemoFieldLang t = new tnxMemoFieldLang();
//        t.setBounds(10, 10, 400, 300);
        t.setBorder(new LineBorder(Color.red));
        f.getContentPane().add(t, BorderLayout.CENTER);
        t.setLang(Arrays.asList("it", "en", "fr"));
        f.pack();

        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }

    public List<JScrollPane> getScroll() {
        return scroll;
    }

    public void setScroll(List<JScrollPane> scroll) {
        this.scroll = scroll;
    }

    public List<JTextArea> getTextarea() {
        return textarea;
    }

    public void setTextarea(List<JTextArea> textarea) {
        this.textarea = textarea;
    }

    public List<JButton> getButtons() {
        return buttons;
    }

    public void setButtons(List<JButton> buttons) {
        this.buttons = buttons;
    }

    public String getDbNomeCampo() {
        return dbNomeCampo;
    }

    public void setDbNomeCampo(String dbNomeCampo) {
        this.dbNomeCampo = dbNomeCampo;
    }

    public String getDbTipoCampo() {
        return dbTipoCampo;
    }

    public void setDbTipoCampo(String dbTipoCampo) {
        this.dbTipoCampo = dbTipoCampo;
    }

    public boolean isDbRiempire() {
        return dbRiempire;
    }

    public void setDbRiempire(boolean dbRiempire) {
        this.dbRiempire = dbRiempire;
    }

    public boolean isDbSalvare() {
        return dbSalvare;
    }

    public void setDbSalvare(boolean dbSalvare) {
        this.dbSalvare = dbSalvare;
    }

    public boolean isDbModificato() {
        return dbModificato;
    }

    public void setDbModificato(boolean dbModificato) {
        this.dbModificato = dbModificato;
    }

    public String getText(String lang) {
        return getLang_area().get(lang).getText();
    }

    public void setText(String text) {
        for (String l : getLang()) {
            JTextArea a = getLang_area().get(l);
            a.setText(text);
        }
    }
    public void setText(String lang, String text) {
        JTextArea a = getLang_area().get(lang);
        a.setText(text);
    }

    public HashMap<String, String> getTextLang() {
        //return lang_area.get(lang).getText();
        HashMap<String, String> ret = new HashMap<String, String>();
        for (String l : getLang()) {
            JTextArea a = getLang_area().get(l);
            ret.put(l, a.getText());
        }
        return ret;
    }
}
