CREATE TABLE `test_ordi_acquisto` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`serie` CHAR(1) NOT NULL DEFAULT '',
	`numero` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`anno` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`fornitore` INT(10) UNSIGNED NULL DEFAULT NULL,
	`fornitore_destinazione` INT(10) UNSIGNED NULL DEFAULT NULL,
	`data` DATE NULL DEFAULT '0000-00-00',
	`data_consegna` VARCHAR(255) NULL DEFAULT NULL,
	`pagamento` VARCHAR(35) NULL DEFAULT NULL,
	`banca_abi` VARCHAR(5) NULL DEFAULT NULL,
	`banca_cab` VARCHAR(5) NULL DEFAULT NULL,
	`banca_cc` VARCHAR(35) NULL DEFAULT NULL,
	`spese_varie` DECIMAL(12,2) NULL DEFAULT NULL,
	`note` TEXT NULL,
	`note_testa` TEXT NULL,
	`note_corpo` TEXT NULL,
	`note_piede` TEXT NULL,
	`totale_imponibile` DECIMAL(12,2) NULL DEFAULT NULL,
	`totale_iva` DECIMAL(12,2) NULL DEFAULT NULL,
	`totale` DECIMAL(12,2) NULL DEFAULT NULL,
	`sconto1` DECIMAL(4,2) NULL DEFAULT NULL,
	`sconto2` DECIMAL(4,2) NULL DEFAULT NULL,
	`riferimento` VARCHAR(255) NULL DEFAULT NULL,
	`sconto3` DECIMAL(4,2) NULL DEFAULT NULL,
	`stato` CHAR(1) NULL DEFAULT NULL,
	`codice_listino` TINYINT(3) UNSIGNED NULL DEFAULT '1',
	`stampato` DATETIME NULL DEFAULT NULL,
	`spese_trasporto` DECIMAL(10,2) NULL DEFAULT NULL,
	`spese_incasso` DECIMAL(10,5) NULL DEFAULT NULL,
	`dest_ragione_sociale` VARCHAR(100) NULL DEFAULT NULL,
	`dest_indirizzo` VARCHAR(50) NULL DEFAULT NULL,
	`dest_cap` VARCHAR(10) NULL DEFAULT NULL,
	`dest_localita` VARCHAR(30) NULL DEFAULT NULL,
	`dest_provincia` CHAR(2) NULL DEFAULT NULL,
	`dest_telefono` VARCHAR(20) NULL DEFAULT NULL,
	`dest_cellulare` VARCHAR(20) NULL DEFAULT NULL,
	`tipo_fattura` TINYINT(4) NULL DEFAULT NULL,
	`aspetto_esteriore_beni` VARCHAR(255) NULL DEFAULT NULL,
	`numero_colli` VARCHAR(30) NULL DEFAULT NULL,
	`peso_lordo` VARCHAR(20) NULL DEFAULT NULL,
	`peso_netto` VARCHAR(20) NULL DEFAULT NULL,
	`vettore1` VARCHAR(255) NULL DEFAULT NULL,
	`porto` VARCHAR(100) NULL DEFAULT NULL,
	`causale_trasporto` VARCHAR(100) NULL DEFAULT NULL,
	`mezzo_consegna` VARCHAR(25) NULL DEFAULT NULL,
	`opzione_riba_dest_diversa` CHAR(1) NULL DEFAULT 'N',
	`note_pagamento` TEXT NULL,
	`agente_codice` INT(11) NULL DEFAULT NULL,
	`agente_percentuale` DECIMAL(5,2) NULL DEFAULT '0.00',
	`doc_tipo` CHAR(2) NULL DEFAULT NULL,
	`doc_serie` CHAR(1) NULL DEFAULT NULL,
	`doc_numero` INT(11) NULL DEFAULT NULL,
	`doc_anno` INT(11) NULL DEFAULT NULL,
	`giorno_pagamento` TINYINT(4) NULL DEFAULT NULL,
	`banca_iban` VARCHAR(100) NULL DEFAULT NULL,
	`stato_ordine` VARCHAR(200) NULL DEFAULT NULL,
	`dest_paese` VARCHAR(2) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)