CREATE TABLE `test_ddt_acquisto` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`serie` CHAR(1) NULL DEFAULT NULL,
	`numero` INT(10) UNSIGNED NULL DEFAULT '0',
	`anno` INT(10) UNSIGNED NULL DEFAULT '0',
	`fornitore` INT(10) UNSIGNED NULL DEFAULT NULL,
	`fornitore_destinazione` INT(10) UNSIGNED NULL DEFAULT NULL,
	`data` DATE NULL DEFAULT '0000-00-00',
	`data_consegna` VARCHAR(255) NULL DEFAULT NULL,
	`pagamento` VARCHAR(35) NULL DEFAULT NULL,
	`spese_varie` DECIMAL(15,5) NULL DEFAULT NULL,
	`note` TEXT NULL,
	`note_testa` TEXT NULL,
	`note_corpo` TEXT NULL,
	`note_piede` TEXT NULL,
	`totale_imponibile` DECIMAL(15,2) NULL DEFAULT NULL,
	`totale_iva` DECIMAL(15,2) NULL DEFAULT NULL,
	`totale` DECIMAL(15,2) NULL DEFAULT NULL,
	`sconto1` DECIMAL(5,2) NULL DEFAULT NULL,
	`sconto2` DECIMAL(5,2) NULL DEFAULT NULL,
	`riferimento` VARCHAR(255) NULL DEFAULT NULL,
	`sconto3` DECIMAL(5,2) NULL DEFAULT NULL,
	`stato` CHAR(1) NULL DEFAULT NULL,
	`codice_listino` TINYINT(3) UNSIGNED NULL DEFAULT '1',
	`stampato` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
	`aspetto_esteriore_beni` VARCHAR(255) NULL DEFAULT NULL,
	`numero_colli` VARCHAR(30) NULL DEFAULT NULL,
	`peso_lordo` VARCHAR(20) NULL DEFAULT NULL,
	`peso_netto` VARCHAR(20) NULL DEFAULT NULL,
	`vettore1` VARCHAR(255) NULL DEFAULT NULL,
	`porto` VARCHAR(100) NULL DEFAULT NULL,
	`causale_trasporto` VARCHAR(100) NULL DEFAULT NULL,
	`spese_trasporto` DECIMAL(15,5) NULL DEFAULT NULL,
	`spese_incasso` DECIMAL(15,5) NULL DEFAULT NULL,
	`mezzo_consegna` VARCHAR(25) NULL DEFAULT NULL,
	`dest_ragione_sociale` VARCHAR(100) NULL DEFAULT NULL,
	`dest_indirizzo` VARCHAR(50) NULL DEFAULT NULL,
	`dest_cap` VARCHAR(10) NULL DEFAULT NULL,
	`dest_localita` VARCHAR(30) NULL DEFAULT NULL,
	`dest_provincia` CHAR(2) NULL DEFAULT NULL,
	`dest_telefono` VARCHAR(20) NULL DEFAULT NULL,
	`dest_cellulare` VARCHAR(20) NULL DEFAULT NULL,
	`fattura_serie` CHAR(1) NULL DEFAULT NULL,
	`fattura_numero` INT(10) UNSIGNED NULL DEFAULT NULL,
	`fattura_anno` INT(10) UNSIGNED NULL DEFAULT NULL,
	`ddt_tv_targa` VARCHAR(30) NULL DEFAULT NULL,
	`giorno_pagamento` TINYINT(4) NULL DEFAULT NULL,
	`banca_iban` VARCHAR(100) NULL DEFAULT NULL,
	`dataoraddt` VARCHAR(50) NULL DEFAULT NULL,
	`dest_paese` VARCHAR(2) NULL DEFAULT NULL,
	`opzione_prezzi_ddt` CHAR(1) NULL DEFAULT 'N',
	`banca_abi` VARCHAR(5) NULL DEFAULT NULL,
	`banca_cab` VARCHAR(5) NULL DEFAULT NULL,
	`banca_cc` VARCHAR(35) NULL DEFAULT NULL,
	`agente_codice` INT(11) NULL DEFAULT NULL,
	`agente_percentuale` DECIMAL(5,2) NULL DEFAULT '0.00',
	`note_pagamento` TEXT NULL,
	PRIMARY KEY (`id`)
)